import type { Challenge } from "../types"

export const WORDS_TECH: Challenge[] = [
  { id: 251, word: "SOFTWARE", tip: "Software / Programa", phonetic: "/ˈsɑːft.wer/", example: "Update your software regularly.", examplePt: "Atualize seu software regularmente." },
  { id: 252, word: "HARDWARE", tip: "Hardware / Equipamento", phonetic: "/ˈhɑːrd.wer/", example: "We upgraded our computer hardware.", examplePt: "Nós atualizamos o hardware do nosso computador." },
  { id: 253, word: "DATABASE", tip: "Banco de dados", phonetic: "/ˈdeɪ.t̬ə.beɪs/", example: "Query the customer database.", examplePt: "Consulte o banco de dados de clientes." },
  { id: 254, word: "NETWORK", tip: "Rede", phonetic: "/ˈnet.wɝːk/", example: "Connect to the office network.", examplePt: "Conecte-se à rede do escritório." },
  { id: 255, word: "SERVER", tip: "Servidor", phonetic: "/ˈsɝː.vɚ/", example: "The web server responded in milliseconds.", examplePt: "O servidor web respondeu em milissegundos." },
  { id: 256, word: "CODE", tip: "Código", phonetic: "/koʊd/", example: "She writes clean and efficient code.", examplePt: "Ela escreve código limpo e eficiente." },
  { id: 257, word: "DEVELOPER", tip: "Desenvolvedor / Programador", phonetic: "/dɪˈvel.ə.pɚ/", example: "He works as a full-stack developer.", examplePt: "Ele trabalha como desenvolvedor full-stack." },
  { id: 258, word: "WEBSITE", tip: "Site / Página na web", phonetic: "/ˈweb.saɪt/", example: "Visit our new official website.", examplePt: "Visite nosso novo site oficial." },
  { id: 259, word: "BROWSER", tip: "Navegador de internet", phonetic: "/ˈbraʊ.zɚ/", example: "Open the link in your web browser.", examplePt: "Abra o link no seu navegador web." },
  { id: 260, word: "PASSWORD", tip: "Senha", phonetic: "/ˈpæs.wɝːd/", example: "Choose a strong and secure password.", examplePt: "Escolha uma senha forte e segura." },
  { id: 261, word: "SECURITY", tip: "Segurança", phonetic: "/səˈkjʊr.ə.t̬i/", example: "Cyber security protects user privacy.", examplePt: "Cibersegurança protege a privacidade do usuário." },
  { id: 262, word: "DOWNLOAD", tip: "Baixar / Download", phonetic: "/ˌdaʊnˈloʊd/", example: "Download the application on your phone.", examplePt: "Baixe o aplicativo no seu celular." },
  { id: 263, word: "UPLOAD", tip: "Enviar arquivo / Upload", phonetic: "/ˈʌp.loʊd/", example: "Upload the project files to the cloud.", examplePt: "Envie os arquivos do projeto para a nuvem." },
  { id: 264, word: "CLOUD", tip: "Nuvem (armazenamento)", phonetic: "/klaʊd/", example: "Our data is stored safely in the cloud.", examplePt: "Nossos dados estão armazenados com segurança na nuvem." },
  { id: 265, word: "ALGORITHM", tip: "Algoritmo", phonetic: "/ˈæl.ɡə.rɪ.ðəm/", example: "The search algorithm is fast and accurate.", examplePt: "O algoritmo de busca é rápido e preciso." },
  { id: 266, word: "APPLICATION", tip: "Aplicativo / App", phonetic: "/ˌæp.ləˈkeɪ.ʃən/", example: "Download this useful mobile application.", examplePt: "Baixe este aplicativo móvel útil." },
  { id: 267, word: "INTERFACE", tip: "Interface", phonetic: "/ˈɪn.t̬ɚ.feɪs/", example: "The user interface is modern and intuitive.", examplePt: "A interface do usuário é moderna e intuitiva." },
  { id: 268, word: "SCREEN", tip: "Tela / Monitor", phonetic: "/skriːn/", example: "Clean your laptop screen gently.", examplePt: "Limpe a tela do seu laptop com cuidado." },
  { id: 269, word: "KEYBOARD", tip: "Teclado", phonetic: "/ˈkiː.bɔːrd/", example: "He types quickly on the mechanical keyboard.", examplePt: "Ele digita rápido no teclado mecânico." },
  { id: 270, word: "MOUSE", tip: "Mouse", phonetic: "/maʊs/", example: "Move the mouse cursor to the button.", examplePt: "Mova o cursor do mouse até o botão." },
  { id: 271, word: "CLICK", tip: "Clicar", phonetic: "/klɪk/", example: "Click here to submit the form.", examplePt: "Clique aqui para enviar o formulário." },
  { id: 272, word: "MEMORY", tip: "Memória", phonetic: "/ˈmem.ər.i/", example: "My computer has 16 gigabytes of memory.", examplePt: "Meu computador tem 16 gigabytes de memória." },
  { id: 273, word: "STORAGE", tip: "Armazenamento", phonetic: "/ˈstɔːr.ɪdʒ/", example: "I need extra cloud storage for photos.", examplePt: "Preciso de mais armazenamento na nuvem para fotos." },
  { id: 274, word: "FILE", tip: "Arquivo", phonetic: "/faɪl/", example: "Save the file before closing the editor.", examplePt: "Salve o arquivo antes de fechar o editor." },
  { id: 275, word: "FOLDER", tip: "Pasta", phonetic: "/ˈfoʊl.dɚ/", example: "Create a new folder on your desktop.", examplePt: "Crie uma nova pasta na sua área de trabalho." },
  { id: 276, word: "LOGIN", tip: "Entrar / Iniciar sessão", phonetic: "/ˈlɑːɡ.ɪn/", example: "Enter your email to login.", examplePt: "Digite seu e-mail para fazer login." },
  { id: 277, word: "LOGOUT", tip: "Sair / Encerrar sessão", phonetic: "/ˈlɑːɡ.aʊt/", example: "Always logout when using shared computers.", examplePt: "Sempre encerre a sessão ao usar computadores compartilhados." },
  { id: 278, word: "UPDATE", tip: "Atualização / Atualizar", phonetic: "/ʌpˈdeɪt/", example: "Install the latest system update.", examplePt: "Instale a atualização mais recente do sistema." },
  { id: 279, word: "SEARCH", tip: "Pesquisar / Busca", phonetic: "/sɝːtʃ/", example: "Search for answers online.", examplePt: "Pesquise por respostas online." },
  { id: 280, word: "ONLINE", tip: "Conectado / Online", phonetic: "/ˌɑːnˈlaɪn/", example: "She is shopping online.", examplePt: "Ela está fazendo compras online." },
  { id: 281, word: "OFFLINE", tip: "Desconectado / Offline", phonetic: "/ˌɑːfˈlaɪn/", example: "This app works even when offline.", examplePt: "Este app funciona mesmo quando desconectado." },
  { id: 282, word: "BACKUP", tip: "Cópia de segurança / Backup", phonetic: "/ˈbæk.ʌp/", example: "Always make a daily backup of your data.", examplePt: "Sempre faça um backup diário dos seus dados." },
  { id: 283, word: "BUG", tip: "Erro no código / Falha", phonetic: "/bʌɡ/", example: "We found and fixed a critical bug.", examplePt: "Encontramos e corrigimos um bug crítico." },
  { id: 284, word: "FEATURE", tip: "Funcionalidade / Recurso", phonetic: "/ˈfiː.tʃɚ/", example: "The new feature improves speech audio.", examplePt: "A nova funcionalidade melhora o áudio da fala." },
  { id: 285, word: "NOTIFICATION", tip: "Notificação", phonetic: "/ˌnoʊ.t̬ə.fəˈkeɪ.ʃən/", example: "You received a new message notification.", examplePt: "Você recebeu uma notificação de nova mensagem." },
  { id: 286, word: "SETTINGS", tip: "Configurações", phonetic: "/ˈset̬.ɪŋz/", example: "Change sound options in app settings.", examplePt: "Altere opções de som nas configurações do app." },
  { id: 287, word: "MESSAGE", tip: "Mensagem", phonetic: "/ˈmes.ɪdʒ/", example: "Send a quick message to your team.", examplePt: "Envie uma mensagem rápida para seu time." },
  { id: 288, word: "BATTERY", tip: "Bateria", phonetic: "/ˈbæt̬.ɚ.i/", example: "Charge your phone before the battery dies.", examplePt: "Carregue seu celular antes que a bateria acabe." },
  { id: 289, word: "CHARGER", tip: "Carregador", phonetic: "/ˈtʃɑːr.dʒɚ/", example: "Do you have a phone charger I can use?", examplePt: "Você tem um carregador de celular que eu possa usar?" },
  { id: 290, word: "HEADPHONES", tip: "Fones de ouvido", phonetic: "/ˈhed.foʊnz/", example: "Put on your headphones to listen to music.", examplePt: "Coloque seus fones de ouvido para ouvir música." },
  { id: 291, word: "MICROPHONE", tip: "Microfone", phonetic: "/ˈmaɪ.krə.foʊn/", example: "Speak clearly into the microphone.", examplePt: "Fale com clareza no microfone." },
  { id: 292, word: "CAMERA", tip: "Câmera", phonetic: "/ˈkæm.rə/", example: "Turn on your video camera during meetings.", examplePt: "Ligue sua câmera de vídeo durante as reuniões." },
  { id: 293, word: "VIDEO", tip: "Vídeo", phonetic: "/ˈvɪd.i.oʊ/", example: "Watch this tutorial video to learn English.", examplePt: "Assista a este vídeo tutorial para aprender inglês." },
  { id: 294, word: "STREAMING", tip: "Transmissão contínua / Streaming", phonetic: "/ˈstriː.mɪŋ/", example: "I love streaming movies and podcasts.", examplePt: "Adoro assistir a filmes e podcasts por streaming." },
  { id: 295, word: "SMARTPHONE", tip: "Celular inteligente / Smartphone", phonetic: "/ˈsmɑːrt.foʊn/", example: "Smartphones make communication easier.", examplePt: "Smartphones tornam a comunicação mais fácil." },
  { id: 296, word: "TABLET", tip: "Tablet", phonetic: "/ˈtæb.lət/", example: "He reads books on his digital tablet.", examplePt: "Ele lê livros em seu tablet digital." },
  { id: 297, word: "ROUTER", tip: "Roteador (Wi-Fi)", phonetic: "/ˈraʊ.t̬ɚ/", example: "Restart the Wi-Fi router to fix the connection.", examplePt: "Reinicie o roteador Wi-Fi para corrigir a conexão." },
  { id: 298, word: "CONNECTION", tip: "Conexão", phonetic: "/kəˈnek.ʃən/", example: "Our internet connection is very stable.", examplePt: "Nossa conexão com a internet é muito estável." },
  { id: 299, word: "DIGITAL", tip: "Digital", phonetic: "/ˈdɪdʒ.ə.t̬əl/", example: "We live in a fast-paced digital world.", examplePt: "Vivemos em um mundo digital acelerado." },
  { id: 300, word: "INNOVATION", tip: "Inovação", phonetic: "/ˌɪn.əˈveɪ.ʃən/", example: "Technological innovation creates new jobs.", examplePt: "Inovação tecnológica cria novos empregos." },
]
