import type { Challenge } from "../types"

export const WORDS_NATURE: Challenge[] = [
  { id: 451, word: "TREE", tip: "Árvore", phonetic: "/triː/", example: "Birds are singing in the tall tree.", examplePt: "Pássaros estão cantando na árvore alta." },
  { id: 452, word: "FOREST", tip: "Floresta / Bosque", phonetic: "/ˈfɔːr.ɪst/", example: "We went for a peaceful walk in the forest.", examplePt: "Fizemos uma caminhada tranquila na floresta." },
  { id: 453, word: "RIVER", tip: "Rio", phonetic: "/ˈrɪv.ɚ/", example: "A clear river flows through the valley.", examplePt: "Um rio de águas límpidas corre pelo vale." },
  { id: 454, word: "LAKE", tip: "Lago", phonetic: "/leɪk/", example: "We rented a small boat on the lake.", examplePt: "Alugamos um pequeno barco no lago." },
  { id: 455, word: "OCEAN", tip: "Oceano / Mar", phonetic: "/ˈoʊ.ʃən/", example: "The vast ocean looked breathtaking at sunset.", examplePt: "O vasto oceano parecia deslumbrante no pôr do sol." },
  { id: 456, word: "MOUNTAIN", tip: "Montanha", phonetic: "/ˈmaʊn.tən/", example: "Snow covers the top of the mountain.", examplePt: "A neve cobre o topo da montanha." },
  { id: 457, word: "SKY", tip: "Céu", phonetic: "/skaɪ/", example: "The blue sky is completely cloudless today.", examplePt: "O céu azul está totalmente sem nuvens hoje." },
  { id: 458, word: "SUN", tip: "Sol", phonetic: "/sʌn/", example: "The morning sun shines brightly.", examplePt: "O sol da manhã brilha intensamente." },
  { id: 459, word: "MOON", tip: "Lua", phonetic: "/muːn/", example: "The full moon lights up the night sky.", examplePt: "A lua cheia ilumina o céu noturno." },
  { id: 460, word: "STAR", tip: "Estrela", phonetic: "/stɑːr/", example: "Look at the brightest star in the sky.", examplePt: "Olhe para a estrela mais brilhante no céu." },
  { id: 461, word: "RAIN", tip: "Chuva / Chover", phonetic: "/reɪn/", example: "I love the smell of fresh rain.", examplePt: "Eu amo o cheiro de chuva fresca." },
  { id: 462, word: "SNOW", tip: "Neve / Nevar", phonetic: "/snoʊ/", example: "Children played happily in the white snow.", examplePt: "As crianças brincaram felizes na neve branca." },
  { id: 463, word: "WIND", tip: "Vento", phonetic: "/wɪnd/", example: "A cool wind blew across the open field.", examplePt: "Um vento fresco soprou pelo campo aberto." },
  { id: 464, word: "CLOUD", tip: "Nuvem", phonetic: "/klaʊd/", example: "Dark clouds indicate a storm is coming.", examplePt: "Nuvens escuras indicam que uma tempestade está chegando." },
  { id: 465, word: "STORM", tip: "Tempestade", phonetic: "/stɔːrm/", example: "We stayed indoors during the heavy storm.", examplePt: "Ficamos dentro de casa durante a forte tempestade." },
  { id: 466, word: "FLOWER", tip: "Flor", phonetic: "/ˈflaʊ.ɚ/", example: "Colorful flowers bloom in spring.", examplePt: "Flores coloridas desabrocham na primavera." },
  { id: 467, word: "GRASS", tip: "Grama / Relva", phonetic: "/ɡræs/", example: "Sit down on the soft green grass.", examplePt: "Sente-se na grama verde e macia." },
  { id: 468, word: "GARDEN", tip: "Jardim / Horta", phonetic: "/ˈɡɑːr.dən/", example: "She plants roses in her garden.", examplePt: "Ela planta rosas no seu jardim." },
  { id: 469, word: "PLANT", tip: "Planta / Plantar", phonetic: "/plænt/", example: "Water the house plants every two days.", examplePt: "Regue as plantas da casa a cada dois dias." },
  { id: 470, word: "LEAF", tip: "Folha (de árvore)", phonetic: "/liːf/", example: "Autumn leaves turn red and gold.", examplePt: "Folhas de outono ficam vermelhas e douradas." },
  { id: 471, word: "DOG", tip: "Cachorro / Cão", phonetic: "/dɑːɡ/", example: "A dog is man's best friend.", examplePt: "O cachorro é o melhor amigo do homem." },
  { id: 472, word: "CAT", tip: "Gato", phonetic: "/kæt/", example: "The cat is sleeping on the sunny sofa.", examplePt: "O gato está dormindo no sofá ensolarado." },
  { id: 473, word: "BIRD", tip: "Pássaro / Ave", phonetic: "/bɝːd/", example: "A bird built a nest in the garden.", examplePt: "Um pássaro construiu um ninho no jardim." },
  { id: 474, word: "HORSE", tip: "Cavalo", phonetic: "/hɔːrs/", example: "He rode a beautiful brown horse.", examplePt: "Ele montou um lindo cavalo marrom." },
  { id: 475, word: "COW", tip: "Vaca", phonetic: "/kaʊ/", example: "Cows are grazing peacefully in the pasture.", examplePt: "Vacas estão pastando tranquilamente no pasto." },
  { id: 476, word: "LION", tip: "Leão", phonetic: "/ˈlaɪ.ən/", example: "The lion is known as the king of the jungle.", examplePt: "O leão é conhecido como o rei da selva." },
  { id: 477, word: "TIGER", tip: "Tigre", phonetic: "/ˈtaɪ.ɡɚ/", example: "The Siberian tiger is a majestic animal.", examplePt: "O tigre siberiano é um animal majestoso." },
  { id: 478, word: "ELEPHANT", tip: "Elefante", phonetic: "/ˈel.ə.fənt/", example: "Elephants are highly intelligent creatures.", examplePt: "Elefantes são criaturas altamente inteligentes." },
  { id: 479, word: "MONKEY", tip: "Macaco", phonetic: "/ˈmʌŋ.ki/", example: "The monkey jumped from branch to branch.", examplePt: "O macaco pulou de galho em galho." },
  { id: 480, word: "BEAR", tip: "Urso", phonetic: "/ber/", example: "Bears hibernate during the cold winter.", examplePt: "Ursos hibernam durante o inverno frio." },
  { id: 481, word: "RABBIT", tip: "Coelho", phonetic: "/ˈræb.ɪt/", example: "A small white rabbit hopped across the lawn.", examplePt: "Um pequeno coelho branco pulou pelo gramado." },
  { id: 482, word: "DOLPHIN", tip: "Golfinho", phonetic: "/ˈdɑːl.fɪn/", example: "Dolphins swam alongside our tour boat.", examplePt: "Golfinhos nadaram ao lado do nosso barco de passeio." },
  { id: 483, word: "WHALE", tip: "Baleia", phonetic: "/weɪl/", example: "The blue whale is the largest mammal on Earth.", examplePt: "A baleia-azul é o maior mamífero da Terra." },
  { id: 484, word: "SHARK", tip: "Tubarão", phonetic: "/ʃɑːrk/", example: "Sharks play a vital role in ocean ecosystems.", examplePt: "Tubarões desempenham um papel vital nos ecossistemas marinhos." },
  { id: 485, word: "EAGLE", tip: "Águia", phonetic: "/ˈiː.ɡəl/", example: "The golden eagle soared high above the cliffs.", examplePt: "A águia-dourada voou alto sobre os penhascos." },
  { id: 486, word: "BUTTERFLY", tip: "Borboleta", phonetic: "/ˈbʌt̬.ɚ.flaɪ/", example: "A colorful butterfly landed gently on the rose.", examplePt: "Uma borboleta colorida pousou suavemente na rosa." },
  { id: 487, word: "BEE", tip: "Abelha", phonetic: "/biː/", example: "Bees make honey and pollinate flowers.", examplePt: "Abelhas produzem mel e polinizam flores." },
  { id: 488, word: "ANT", tip: "Formiga", phonetic: "/ænt/", example: "Ants are hardworking and organized insects.", examplePt: "Formigas são insetos trabalhadores e organizados." },
  { id: 489, word: "DESERT", tip: "Deserto", phonetic: "/ˈdez.ɚt/", example: "The Sahara is the largest hot desert.", examplePt: "O Saara é o maior deserto quente." },
  { id: 490, word: "VALLEY", tip: "Vale", phonetic: "/ˈvæl.i/", example: "The lush green valley is peaceful.", examplePt: "O exuberante vale verde é muito tranquilo." },
  { id: 491, word: "WATERFALL", tip: "Cachoeira / Cascata", phonetic: "/ˈwɑː.t̬ɚ.fɑːl/", example: "The sound of the roaring waterfall was loud.", examplePt: "O som da cachoeira imponente era alto." },
  { id: 492, word: "SUNRISE", tip: "Nascer do sol", phonetic: "/ˈsʌn.raɪz/", example: "We woke up early to watch the sunrise.", examplePt: "Acordamos cedo para assistir ao nascer do sol." },
  { id: 493, word: "SUNSET", tip: "Pôr do sol", phonetic: "/ˈsʌn.set/", example: "The sunset over the beach was spectacular.", examplePt: "O pôr do sol na praia foi espetacular." },
  { id: 494, word: "SPRING", tip: "Primavera", phonetic: "/sprɪŋ/", example: "Spring brings warm weather and blooming trees.", examplePt: "A primavera traz clima ameno e árvores floridas." },
  { id: 495, word: "SUMMER", tip: "Verão", phonetic: "/ˈsʌm.ɚ/", example: "We go swimming in the lake during summer.", examplePt: "Nós nadamos no lago durante o verão." },
  { id: 496, word: "AUTUMN", tip: "Outono", phonetic: "/ˈɑː.t̬əm/", example: "Autumn is famous for harvest festivals.", examplePt: "O outono é famoso pelas festas de colheita." },
  { id: 497, word: "WINTER", tip: "Inverno", phonetic: "/ˈwɪn.t̬ɚ/", example: "Winter brings freezing temperatures.", examplePt: "O inverno traz temperaturas congelantes." },
  { id: 498, word: "EARTH", tip: "Terra (planeta / solo)", phonetic: "/ɝːθ/", example: "We must protect Planet Earth.", examplePt: "Devemos proteger o Planeta Terra." },
  { id: 499, word: "ISLAND", tip: "Ilha", phonetic: "/ˈaɪ.lənd/", example: "A tropical island with crystal blue water.", examplePt: "Uma ilha tropical com águas cristalinas." },
  { id: 500, word: "RAINBOW", tip: "Arco-íris", phonetic: "/ˈreɪn.boʊ/", example: "A vibrant rainbow appeared right after the storm.", examplePt: "Um arco-íris vibrante apareceu logo após a tempestade." },
]
