import type { Challenge } from "../types"

export const WORDS_FOOD: Challenge[] = [
  { id: 101, word: "BREAKFAST", tip: "Café da manhã", phonetic: "/ˈbrek.fəst/", example: "I have breakfast at 7 AM.", examplePt: "Eu tomo café da manhã às 7h." },
  { id: 102, word: "LUNCH", tip: "Almoço", phonetic: "/lʌntʃ/", example: "Let's meet for lunch today.", examplePt: "Vamos nos encontrar para o almoço hoje." },
  { id: 103, word: "DINNER", tip: "Jantar", phonetic: "/ˈdɪn.ɚ/", example: "We cooked dinner together.", examplePt: "Nós cozinhamos o jantar juntos." },
  { id: 104, word: "CHEESE", tip: "Queijo", phonetic: "/tʃiːz/", example: "I like extra cheese on my pizza.", examplePt: "Gosto de queijo extra na minha pizza." },
  { id: 105, word: "BUTTER", tip: "Manteiga", phonetic: "/ˈbʌt̬.ɚ/", example: "Spread butter on the warm bread.", examplePt: "Passe manteiga no pão quentinho." },
  { id: 106, word: "CHICKEN", tip: "Frango", phonetic: "/ˈtʃɪk.ɪn/", example: "We ordered grilled chicken for lunch.", examplePt: "Pedimos frango grelhado no almoço." },
  { id: 107, word: "BEEF", tip: "Carne bovina", phonetic: "/biːf/", example: "The roast beef is tender and juicy.", examplePt: "A carne assada está macia e suculenta." },
  { id: 108, word: "FISH", tip: "Peixe", phonetic: "/fɪʃ/", example: "Fresh fish is rich in nutrients.", examplePt: "Peixe fresco é rico em nutrientes." },
  { id: 109, word: "EGG", tip: "Ovo", phonetic: "/eɡ/", example: "I eat two boiled eggs every morning.", examplePt: "Como dois ovos cozidos toda manhã." },
  { id: 110, word: "RICE", tip: "Arroz", phonetic: "/raɪs/", example: "Rice and beans is a classic dish.", examplePt: "Arroz com feijão é um prato clássico." },
  { id: 111, word: "BEANS", tip: "Feijão", phonetic: "/biːnz/", example: "Black beans are very delicious.", examplePt: "Feijão preto é muito gostoso." },
  { id: 112, word: "SOUP", tip: "Sopa", phonetic: "/suːp/", example: "Hot soup is great on a cold evening.", examplePt: "Sopa quente é ótima em uma noite fria." },
  { id: 113, word: "SALAD", tip: "Salada", phonetic: "/ˈsæl.əd/", example: "She ordered a fresh green salad.", examplePt: "Ela pediu uma salada verde fresca." },
  { id: 114, word: "POTATO", tip: "Batata", phonetic: "/pəˈteɪ.toʊ/", example: "Mashed potatoes are my favorite side dish.", examplePt: "Purê de batatas é meu acompanhamento favorito." },
  { id: 115, word: "TOMATO", tip: "Tomate", phonetic: "/təˈmeɪ.toʊ/", example: "We picked ripe tomatoes from the garden.", examplePt: "Colhemos tomates maduros da horta." },
  { id: 116, word: "ONION", tip: "Cebola", phonetic: "/ˈʌn.jən/", example: "Chop the onion into small pieces.", examplePt: "Pique a cebola em pedaços pequenos." },
  { id: 117, word: "GARLIC", tip: "Alho", phonetic: "/ˈɡɑːr.lɪk/", example: "Garlic adds great flavor to sauces.", examplePt: "Alho dá um ótimo sabor aos molhos." },
  { id: 118, word: "APPLE", tip: "Maçã", phonetic: "/ˈæp.əl/", example: "An apple a day keeps the doctor away.", examplePt: "Uma maçã por dia mantém o médico longe." },
  { id: 119, word: "BANANA", tip: "Banana", phonetic: "/bəˈnæn.ə/", example: "Bananas are rich in potassium.", examplePt: "Bananas são ricas em potássio." },
  { id: 120, word: "ORANGE", tip: "Laranja", phonetic: "/ˈɔːr.ɪndʒ/", example: "I drink fresh orange juice.", examplePt: "Eu bebo suco de laranja natural." },
  { id: 121, word: "STRAWBERRY", tip: "Morango", phonetic: "/ˈstrɑːˌber.i/", example: "Strawberries with cream taste amazing.", examplePt: "Morangos com creme têm um sabor incrível." },
  { id: 122, word: "JUICE", tip: "Suco", phonetic: "/dʒuːs/", example: "Would you like a glass of apple juice?", examplePt: "Você gostaria de um copo de suco de maçã?" },
  { id: 123, word: "TEA", tip: "Chá", phonetic: "/tiː/", example: "Green tea helps you relax.", examplePt: "Chá verde ajuda a relaxar." },
  { id: 124, word: "WINE", tip: "Vinho", phonetic: "/waɪn/", example: "Red wine pairs well with pasta.", examplePt: "Vinho tinto combina bem com massas." },
  { id: 125, word: "BEER", tip: "Cerveja", phonetic: "/bɪr/", example: "A cold beer on a hot sunny day.", examplePt: "Uma cerveja gelada em um dia quente de sol." },
  { id: 126, word: "SALT", tip: "Sal", phonetic: "/sɑːlt/", example: "Pass the salt, please.", examplePt: "Passe o sal, por favor." },
  { id: 127, word: "PEPPER", tip: "Pimenta", phonetic: "/ˈpep.ɚ/", example: "Add a pinch of black pepper.", examplePt: "Adicione uma pitada de pimenta-do-reino." },
  { id: 128, word: "OIL", tip: "Óleo / Azeite", phonetic: "/ɔɪl/", example: "Cook with extra virgin olive oil.", examplePt: "Cozinhe com azeite de oliva extravirgem." },
  { id: 129, word: "PIZZA", tip: "Pizza", phonetic: "/ˈpiːt.sə/", example: "We ordered pepperoni pizza.", examplePt: "Pedimos pizza de pepperoni." },
  { id: 130, word: "BURGER", tip: "Hambúrguer", phonetic: "/ˈbɝː.ɡɚ/", example: "A grilled burger with crispy fries.", examplePt: "Um hambúrguer grelhado com batatas crocantes." },
  { id: 131, word: "PASTA", tip: "Massa / Macarrão", phonetic: "/ˈpɑː.stə/", example: "Italian pasta with tomato basil sauce.", examplePt: "Massa italiana com molho de tomate e manjericão." },
  { id: 132, word: "DESSERT", tip: "Sobremesa", phonetic: "/dɪˈzɝːt/", example: "Save room for dessert!", examplePt: "Guarde espaço para a sobremesa!" },
  { id: 133, word: "CAKE", tip: "Bolo", phonetic: "/keɪk/", example: "Chocolate cake for the birthday party.", examplePt: "Bolo de chocolate para a festa de aniversário." },
  { id: 134, word: "ICE CREAM", tip: "Sorvete", phonetic: "/ˈaɪs ˌkriːm/", example: "Vanilla ice cream on a warm day.", examplePt: "Sorvete de baunilha em um dia quente." },
  { id: 135, word: "CHOCOLATE", tip: "Chocolate", phonetic: "/ˈtʃɑːk.lət/", example: "Dark chocolate is my absolute favorite.", examplePt: "Chocolate amargo é o meu favorito absoluto." },
  { id: 136, word: "SNACK", tip: "Lanche / Petisco", phonetic: "/snæk/", example: "Grab a healthy snack before working out.", examplePt: "Pegue um lanche saudável antes de treinar." },
  { id: 137, word: "WAITER", tip: "Garçom", phonetic: "/ˈweɪ.t̬ɚ/", example: "The waiter took our dinner order.", examplePt: "O garçom anotou nosso pedido de jantar." },
  { id: 138, word: "WAITRESS", tip: "Garçonete", phonetic: "/ˈweɪ.trəs/", example: "The waitress was very polite and helpful.", examplePt: "A garçonete foi muito educada e prestativa." },
  { id: 139, word: "CHEF", tip: "Chefe de cozinha", phonetic: "/ʃef/", example: "The executive chef prepared a special meal.", examplePt: "O chef executivo preparou uma refeição especial." },
  { id: 140, word: "FORK", tip: "Garfo", phonetic: "/fɔːrk/", example: "Set the fork to the left of the plate.", examplePt: "Coloque o garfo à esquerda do prato." },
  { id: 141, word: "KNIFE", tip: "Faca", phonetic: "/naɪf/", example: "Use a sharp knife to cut meat.", examplePt: "Use uma faca afiada para cortar a carne." },
  { id: 142, word: "SPOON", tip: "Colher", phonetic: "/spuːn/", example: "Eat your soup with a spoon.", examplePt: "Coma sua sopa com uma colher." },
  { id: 143, word: "PLATE", tip: "Prato", phonetic: "/pleɪt/", example: "Put the hot food on the plate.", examplePt: "Coloque a comida quente no prato." },
  { id: 144, word: "GLASS", tip: "Copo / Taça", phonetic: "/ɡlæs/", example: "A tall glass of ice water.", examplePt: "Um copo alto de água gelada." },
  { id: 145, word: "NAPKIN", tip: "Guardanapo", phonetic: "/ˈnæp.kɪn/", example: "Wipe your hands with a clean napkin.", examplePt: "Limpe suas mãos com um guardanapo limpo." },
  { id: 146, word: "DELICIOUS", tip: "Delicioso / Saboroso", phonetic: "/dɪˈlɪʃ.əs/", example: "This homemade pasta is delicious!", examplePt: "Esta massa caseira está deliciosa!" },
  { id: 147, word: "SWEET", tip: "Doce", phonetic: "/swiːt/", example: "Ripe mangoes taste sweet and juicy.", examplePt: "Mangas maduras têm um sabor doce e suculento." },
  { id: 148, word: "SPICY", tip: "Picante / Apimentado", phonetic: "/ˈspaɪ.si/", example: "Mexican food can be very spicy.", examplePt: "Comida mexicana pode ser bem picante." },
  { id: 149, word: "TASTY", tip: "Gostoso / Saboroso", phonetic: "/ˈteɪ.sti/", example: "Everything on the menu is tasty.", examplePt: "Tudo no cardápio é saboroso." },
  { id: 150, word: "HUNGRY", tip: "Com fome", phonetic: "/ˈhʌŋ.ɡri/", example: "I am hungry; let's order food.", examplePt: "Estou com fome; vamos pedir comida." },
]
