import type { Challenge } from "../types"

export const WORDS_ENTERTAINMENT: Challenge[] = [
  { id: 651, word: "MOVIE", tip: "Filme", phonetic: "/ˈmuː.vi/", example: "Let's watch an action movie tonight.", examplePt: "Vamos assistir a um filme de ação hoje à noite." },
  { id: 652, word: "CINEMA", tip: "Cinema", phonetic: "/ˈsɪn.ə.mɑː/", example: "We bought popcorn at the cinema.", examplePt: "Compramos pipoca no cinema." },
  { id: 653, word: "ACTOR", tip: "Ator", phonetic: "/ˈæk.tɚ/", example: "He is a famous Hollywood actor.", examplePt: "Ele é um famoso ator de Hollywood." },
  { id: 654, word: "ACTRESS", tip: "Atriz", phonetic: "/ˈæk.trəs/", example: "The lead actress delivered an emotional performance.", examplePt: "A atriz principal entregou uma atuação emocionante." },
  { id: 655, word: "DIRECTOR", tip: "Diretor (de cinema/teatro)", phonetic: "/daɪˈrek.tɚ/", example: "The film director won several awards.", examplePt: "O diretor do filme ganhou vários prêmios." },
  { id: 656, word: "SOUNDTRACK", tip: "Trilha sonora", phonetic: "/ˈsaʊnd.træk/", example: "The movie soundtrack was composed by an orchestra.", examplePt: "A trilha sonora do filme foi composta por uma orquestra." },
  { id: 657, word: "POP CULTURE", tip: "Cultura pop", phonetic: "/ˌpɑːp ˈkʌl.tʃɚ/", example: "Superheroes are a huge part of modern pop culture.", examplePt: "Super-heróis são uma grande parte da cultura pop moderna." },
  { id: 658, word: "BLOCKBUSTER", tip: "Sucesso de bilheteria / Grande produção", phonetic: "/ˈblɑːkˌbʌs.tɚ/", example: "The latest superhero movie is a summer blockbuster.", examplePt: "O último filme de super-herói é um grande sucesso de bilheteria." },
  { id: 659, word: "PLOT TWIST", tip: "Reviravolta na história", phonetic: "/ˈplɑːt ˌtwɪst/", example: "The ending had an unexpected plot twist.", examplePt: "O final teve uma reviravolta inesperada na história." },
  { id: 660, word: "SERIES", tip: "Série de TV / Streaming", phonetic: "/ˈsɪr.iːz/", example: "I binged the whole comedy series over the weekend.", examplePt: "Maratonei a série de comédia inteira no fim de semana." },
  { id: 661, word: "EPISODE", tip: "Episódio", phonetic: "/ˈep.ə.soʊd/", example: "Do not miss the season finale episode tonight.", examplePt: "Não perca o episódio final da temporada hoje à noite." },
  { id: 662, word: "SEASON", tip: "Temporada", phonetic: "/ˈsiː.zən/", example: "Season three premieres next month.", examplePt: "A terceira temporada estreia no próximo mês." },
  { id: 663, word: "CONCERT", tip: "Show / Concerto musical", phonetic: "/ˈkɑːn.sɚt/", example: "We got front row tickets for the rock concert.", examplePt: "Conseguimos ingressos na primeira fileira para o show de rock." },
  { id: 664, word: "BAND", tip: "Banda musical", phonetic: "/bænd/", example: "The live band played our favorite songs.", examplePt: "A banda ao vivo tocou nossas músicas favoritas." },
  { id: 665, word: "SINGER", tip: "Cantor / Cantora", phonetic: "/ˈsɪŋ.ɚ/", example: "The singer has an extraordinary vocal range.", examplePt: "A cantora tem um alcance vocal extraordinário." },
  { id: 666, word: "ALBUM", tip: "Álbum musical / Disco", phonetic: "/ˈæl.bəm/", example: "Her new album reached number one on the charts.", examplePt: "O novo álbum dela alcançou o primeiro lugar nas paradas." },
  { id: 667, word: "LYRICS", tip: "Letra da música", phonetic: "/ˈlɪr.ɪks/", example: "Singing along with English lyrics improves pronunciation.", examplePt: "Cantar junto com a letra em inglês melhora a pronúncia." },
  { id: 668, word: "GUITAR", tip: "Violão / Guitarra", phonetic: "/ɡɪˈtɑːr/", example: "He plays the acoustic guitar beautifully.", examplePt: "Ele toca violão maravilhosamente." },
  { id: 669, word: "PIANO", tip: "Piano", phonetic: "/piˈæn.oʊ/", example: "Classical piano music helps me concentrate.", examplePt: "Música clássica de piano me ajuda a concentrar." },
  { id: 670, word: "DRUMS", tip: "Bateria (instrumento)", phonetic: "/drʌmz/", example: "The rhythmic beats on the drums were energetic.", examplePt: "As batidas rítmicas na bateria eram enérgicas." },
  { id: 671, word: "THEATER", tip: "Teatro", phonetic: "/ˈθiː.ə.t̬ɚ/", example: "We saw a captivating play at the historic theater.", examplePt: "Assistimos a uma peça cativante no teatro histórico." },
  { id: 672, word: "STAGE", tip: "Palco", phonetic: "/steɪdʒ/", example: "The actors walked out onto the illuminated stage.", examplePt: "Os atores entraram no palco iluminado." },
  { id: 673, word: "AUDIENCE", tip: "Público / Plateia", phonetic: "/ˈɑː.di.əns/", example: "The audience gave a standing ovation at the end.", examplePt: "A plateia aplaudiu de pé no final." },
  { id: 674, word: "APPLAUSE", tip: "Aplausos / Palmas", phonetic: "/əˈplɑːz/", example: "Loud applause filled the concert hall.", examplePt: "Fortes aplausos ecoaram pela sala de concertos." },
  { id: 675, word: "POPCORN", tip: "Pipoca", phonetic: "/ˈpɑːp.kɔːrn/", example: "Butter popcorn is the ultimate movie treat.", examplePt: "Pipoca na manteiga é o melhor acompanhamento para filmes." },
  { id: 676, word: "TRAILER", tip: "Trailer (prévias de filme)", phonetic: "/ˈtreɪ.lɚ/", example: "The movie trailer looked exciting and visually stunning.", examplePt: "O trailer do filme parecia empolgante e visualmente deslumbrante." },
  { id: 677, word: "PREMIERE", tip: "Estreia / Pré-estreia", phonetic: "/prɪˈmɪr/", example: "Celebrities attended the red carpet movie premiere.", examplePt: "Celebridades compareceram à pré-estreia no tapete vermelho." },
  { id: 678, word: "DOCUMENTARY", tip: "Documentário", phonetic: "/ˌdɑː.kjəˈmen.t̬ɚ.i/", example: "We watched a fascinating nature documentary.", examplePt: "Assistimos a um documentário fascinante sobre a natureza." },
  { id: 679, word: "ANIMATION", tip: "Animação / Desenho animado", phonetic: "/ˌæn.əˈmeɪ.ʃən/", example: "Disney created heartwarming animated movies.", examplePt: "A Disney criou filmes de animação emocionantes." },
  { id: 680, word: "COMEDY", tip: "Comédia", phonetic: "/ˈkɑː.mə.di/", example: "A good stand-up comedy special will make you laugh.", examplePt: "Um bom especial de comédia stand-up fará você rir." },
  { id: 681, word: "DRAMA", tip: "Drama", phonetic: "/ˈdræm.ə/", example: "The intense drama series kept me on the edge.", examplePt: "A intensa série de drama me prendeu do início ao fim." },
  { id: 682, word: "HORROR", tip: "Terror / Horror", phonetic: "/ˈhɔːr.ɚ/", example: "Do you like watching scary horror films in the dark?", examplePt: "Você gosta de assistir a filmes assustadores de terror no escuro?" },
  { id: 683, word: "THRILLER", tip: "Suspense", phonetic: "/ˈθrɪl.ɚ/", example: "A gripping psychological thriller novel.", examplePt: "Um romance de suspense psicológico envolvente." },
  { id: 684, word: "ACTION", tip: "Ação", phonetic: "/ˈæk.ʃən/", example: "Fast cars and thrilling action scenes.", examplePt: "Carros velozes e cenas de ação emocionantes." },
  { id: 685, word: "FANTASY", tip: "Fantasia / Ficção fantástica", phonetic: "/ˈfæn.tə.si/", example: "Dragons and wizards in an epic fantasy universe.", examplePt: "Dragões e magos em um épico universo de fantasia." },
  { id: 686, word: "SCI-FI", tip: "Ficção científica", phonetic: "/ˌsaɪˈfaɪ/", example: "Space travel and futuristic sci-fi technology.", examplePt: "Viagens espaciais e tecnologia futurista de ficção científica." },
  { id: 687, word: "CELEBRITY", tip: "Celebridade / Famoso", phonetic: "/səˈleb.rə.t̬i/", example: "The international celebrity signed autographs for fans.", examplePt: "A celebridade internacional deu autógrafos para os fãs." },
  { id: 688, word: "FESTIVAL", tip: "Festival cultural / musical", phonetic: "/ˈfes.tə.vəl/", example: "Thousands attended the summer music festival.", examplePt: "Milhares compareceram ao festival de música de verão." },
  { id: 689, word: "SUBTITLES", tip: "Legendas", phonetic: "/ˈsʌbˌtaɪ.təlz/", example: "Watching movies with English subtitles boosts listening.", examplePt: "Assistir filmes com legendas em inglês turbina a compreensão auditiva." },
  { id: 690, word: "DUBBED", tip: "Dublado", phonetic: "/dʌbd/", example: "Do you prefer original audio or dubbed voices?", examplePt: "Você prefere áudio original ou vozes dubladas?" },
  { id: 691, word: "STREAMING SERVICE", tip: "Serviço de streaming", phonetic: "/ˈstriː.mɪŋ ˌsɝː.vɪs/", example: "Subscribe to our streaming service for movies.", examplePt: "Assine nosso serviço de streaming para filmes." },
  { id: 692, word: "PODCAST", tip: "Podcast", phonetic: "/ˈpɑːd.kæst/", example: "I listen to English learning podcasts on my commute.", examplePt: "Ouço podcasts de aprendizado de inglês no meu trajeto." },
  { id: 693, word: "VIDEOGAME", tip: "Videogame / Jogo eletrônico", phonetic: "/ˈvɪd.i.oʊˌɡeɪm/", example: "Playing story-rich videogames helps learn English.", examplePt: "Jogar videogames com boas histórias ajuda a aprender inglês." },
  { id: 694, word: "GRAPHICS", tip: "Gráficos visuais", phonetic: "/ˈɡræf.ɪks/", example: "The 3D graphics in modern games look realistic.", examplePt: "Os gráficos 3D nos jogos modernos parecem realistas." },
  { id: 695, word: "MUSEUM EXHIBIT", tip: "Exposição em museu", phonetic: "/mjuːˈziː.əm ɪɡˌzɪb.ɪt/", example: "We visited an ancient Egyptian museum exhibit.", examplePt: "Visitamos uma exposição sobre o Antigo Egito no museu." },
  { id: 696, word: "ART GALLERY", tip: "Galeria de arte", phonetic: "/ˈɑːrt ˌɡæl.ɚ.i/", example: "Local painters showcase work at the art gallery.", examplePt: "Pintores locais exibem seus trabalhos na galeria de arte." },
  { id: 697, word: "SCULPTURE", tip: "Escultura", phonetic: "/ˈskʌlp.tʃɚ/", example: "A magnificent marble sculpture in the square.", examplePt: "Uma magnífica escultura de mármore na praça." },
  { id: 698, word: "PAINTING", tip: "Pintura / Quadro", phonetic: "/ˈpeɪn.t̬ɪŋ/", example: "The famous oil painting hangs in the Louvre.", examplePt: "A famosa pintura a óleo está pendurada no Louvre." },
  { id: 699, word: "CIRCUS", tip: "Circo", phonetic: "/ˈsɝː.kəs/", example: "Acrobats performed daring tricks at the circus.", examplePt: "Acrobatas realizaram truques ousados no circo." },
  { id: 700, word: "SHOWTIME", tip: "Hora do show / Sessão", phonetic: "/ˈʃoʊ.taɪm/", example: "Get your popcorn ready, it is showtime!", examplePt: "Prepare sua pipoca, é hora do show!" },
]
