import type { Challenge } from "../types"

export const WORDS_DAILY: Challenge[] = [
  { id: 1, word: "HOUSE", tip: "Casa", phonetic: "/haʊs/", example: "I am going to my house.", examplePt: "Estou indo para minha casa." },
  { id: 2, word: "ROOM", tip: "Quarto / Cômodo", phonetic: "/ruːm/", example: "My room is very quiet.", examplePt: "Meu quarto é muito silencioso." },
  { id: 3, word: "KITCHEN", tip: "Cozinha", phonetic: "/ˈkɪtʃ.ən/", example: "She is cooking in the kitchen.", examplePt: "Ela está cozinhando na cozinha." },
  { id: 4, word: "BATHROOM", tip: "Banheiro", phonetic: "/ˈbæθ.ruːm/", example: "Where is the bathroom?", examplePt: "Onde fica o banheiro?" },
  { id: 5, word: "WINDOW", tip: "Janela", phonetic: "/ˈwɪn.doʊ/", example: "Please open the window.", examplePt: "Por favor, abra a janela." },
  { id: 6, word: "DOOR", tip: "Porta", phonetic: "/dɔːr/", example: "Close the door, please.", examplePt: "Feche a porta, por favor." },
  { id: 7, word: "BED", tip: "Cama", phonetic: "/bed/", example: "Time to go to bed.", examplePt: "Hora de ir para a cama." },
  { id: 8, word: "TABLE", tip: "Mesa", phonetic: "/ˈteɪ.bəl/", example: "The keys are on the table.", examplePt: "As chaves estão sobre a mesa." },
  { id: 9, word: "CHAIR", tip: "Cadeira", phonetic: "/tʃer/", example: "Take a seat on this chair.", examplePt: "Sente-se nesta cadeira." },
  { id: 10, word: "LIGHT", tip: "Luz", phonetic: "/laɪt/", example: "Turn on the light, please.", examplePt: "Ligue a luz, por favor." },
  { id: 11, word: "FOOD", tip: "Comida", phonetic: "/fuːd/", example: "The food is delicious.", examplePt: "A comida está deliciosa." },
  { id: 12, word: "FRIDGE", tip: "Geladeira", phonetic: "/frɪdʒ/", example: "Put the milk in the fridge.", examplePt: "Coloque o leite na geladeira." },
  { id: 13, word: "WATER", tip: "Água", phonetic: "/ˈwɔː.tər/", example: "Drink plenty of water every day.", examplePt: "Beba bastante água todos os dias." },
  { id: 14, word: "BREAD", tip: "Pão", phonetic: "/bred/", example: "I love fresh bread in the morning.", examplePt: "Eu adoro pão fresco de manhã." },
  { id: 15, word: "COFFEE", tip: "Café", phonetic: "/ˈkɑː.fi/", example: "I need a cup of hot coffee.", examplePt: "Preciso de uma xícara de café quente." },
  { id: 16, word: "MILK", tip: "Leite", phonetic: "/mɪlk/", example: "Do you take milk with your tea?", examplePt: "Você toma leite com seu chá?" },
  { id: 17, word: "SUGAR", tip: "Açúcar", phonetic: "/ˈʃʊɡ.ər/", example: "No sugar in my coffee, please.", examplePt: "Sem açúcar no meu café, por favor." },
  { id: 18, word: "FRUIT", tip: "Fruta", phonetic: "/fruːt/", example: "Fresh fruit is healthy.", examplePt: "Fruta fresca é saudável." },
  { id: 19, word: "CLOTHES", tip: "Roupas", phonetic: "/kloʊðz/", example: "I bought new clothes today.", examplePt: "Comprei roupas novas hoje." },
  { id: 20, word: "SHOES", tip: "Sapatos", phonetic: "/ʃuːz/", example: "These shoes are very comfortable.", examplePt: "Estes sapatos são muito confortáveis." },
  { id: 21, word: "PHONE", tip: "Telefone / Celular", phonetic: "/foʊn/", example: "My phone battery is low.", examplePt: "A bateria do meu telefone está fraca." },
  { id: 22, word: "KEYS", tip: "Chaves", phonetic: "/kiːz/", example: "I cannot find my car keys.", examplePt: "Não consigo encontrar as chaves do meu carro." },
  { id: 23, word: "WALL", tip: "Parede", phonetic: "/wɔːl/", example: "We painted the wall white.", examplePt: "Pintamos a parede de branco." },
  { id: 24, word: "FLOOR", tip: "Chão / Piso", phonetic: "/flɔːr/", example: "Keep your bag off the floor.", examplePt: "Mantenha sua bolsa fora do chão." },
  { id: 25, word: "CLOCK", tip: "Relógio (de parede)", phonetic: "/klɑːk/", example: "Look at the clock on the wall.", examplePt: "Olhe para o relógio na parede." },
  { id: 26, word: "TV", tip: "Televisão", phonetic: "/ˌtiːˈviː/", example: "Let's watch a movie on TV.", examplePt: "Vamos assistir a um filme na TV." },
  { id: 27, word: "COMPUTER", tip: "Computador", phonetic: "/kəmˈpjuː.tər/", example: "I work on my computer every day.", examplePt: "Eu trabalho no meu computador todos os dias." },
  { id: 28, word: "BAG", tip: "Bolsa / Mochila", phonetic: "/bæɡ/", example: "Put your books inside the bag.", examplePt: "Coloque seus livros dentro da bolsa." },
  { id: 29, word: "SOAP", tip: "Sabão / Sabonete", phonetic: "/soʊp/", example: "Wash your hands with soap.", examplePt: "Lave suas mãos com sabonete." },
  { id: 30, word: "TOWEL", tip: "Toalha", phonetic: "/ˈtaʊ.əl/", example: "Here is a clean towel for you.", examplePt: "Aqui está uma toalha limpa para você." },
  { id: 31, word: "MIRROR", tip: "Espelho", phonetic: "/ˈmɪr.ər/", example: "She looked in the mirror.", examplePt: "Ela se olhou no espelho." },
  { id: 32, word: "BRUSH", tip: "Escova", phonetic: "/brʌʃ/", example: "I need to brush my hair.", examplePt: "Preciso escovar meu cabelo." },
  { id: 33, word: "TOOTHPASTE", tip: "Creme dental", phonetic: "/ˈtuːθ.peɪst/", example: "We need to buy more toothpaste.", examplePt: "Precisamos comprar mais creme dental." },
  { id: 34, word: "SHOWER", tip: "Chuveiro / Banho", phonetic: "/ˈʃaʊ.ər/", example: "I take a shower every morning.", examplePt: "Eu tomo um banho todas as manhãs." },
  { id: 35, word: "CAR", tip: "Carro", phonetic: "/kɑːr/", example: "His car is parked outside.", examplePt: "O carro dele está estacionado lá fora." },
  { id: 36, word: "BUS", tip: "Ônibus", phonetic: "/bʌs/", example: "I take the bus to work.", examplePt: "Eu pego o ônibus para o trabalho." },
  { id: 37, word: "STREET", tip: "Rua", phonetic: "/striːt/", example: "They live on the main street.", examplePt: "Eles moram na rua principal." },
  { id: 38, word: "SHOP", tip: "Loja", phonetic: "/ʃɑːp/", example: "This shop sells fresh bread.", examplePt: "Esta loja vende pão fresco." },
  { id: 39, word: "SUPERMARKET", tip: "Supermercado", phonetic: "/ˈsuː.pɚˌmɑːr.kɪt/", example: "I am going to the supermarket.", examplePt: "Estou indo ao supermercado." },
  { id: 40, word: "MONEY", tip: "Dinheiro", phonetic: "/ˈmʌn.i/", example: "Save some money for the future.", examplePt: "Guarde algum dinheiro para o futuro." },
  { id: 41, word: "PEN", tip: "Caneta", phonetic: "/pen/", example: "Can I borrow your pen?", examplePt: "Posso pegar sua caneta emprestada?" },
  { id: 42, word: "BOOK", tip: "Livro", phonetic: "/bʊk/", example: "I am reading an interesting book.", examplePt: "Estou lendo um livro interessante." },
  { id: 43, word: "NEWSPAPER", tip: "Jornal", phonetic: "/ˈnuːzˌpeɪ.pər/", example: "He reads the newspaper every day.", examplePt: "Ele lê o jornal todos os dias." },
  { id: 44, word: "PAPER", tip: "Papel", phonetic: "/ˈpeɪ.pər/", example: "Write your name on the paper.", examplePt: "Escreva seu nome no papel." },
  { id: 45, word: "HAND", tip: "Mão", phonetic: "/hænd/", example: "Hold my hand.", examplePt: "Segure minha mão." },
  { id: 46, word: "HEAD", tip: "Cabeça", phonetic: "/hed/", example: "I have a slight headache.", examplePt: "Estou com uma leve dor de cabeça." },
  { id: 47, word: "FACE", tip: "Rosto", phonetic: "/feɪs/", example: "He washed his face with cold water.", examplePt: "Ele lavou o rosto com água fria." },
  { id: 48, word: "EYES", tip: "Olhos", phonetic: "/aɪz/", example: "She has beautiful blue eyes.", examplePt: "Ela tem lindos olhos azuis." },
  { id: 49, word: "HAIR", tip: "Cabelo", phonetic: "/her/", example: "She has long curly hair.", examplePt: "Ela tem cabelos longos e cacheados." },
  { id: 50, word: "FAMILY", tip: "Família", phonetic: "/ˈfæm.əl.i/", example: "Family is very important to me.", examplePt: "Família é muito importante para mim." },
]
