import type { Challenge } from "../types"

export const WORDS_FEELINGS: Challenge[] = [
  { id: 301, word: "HAPPY", tip: "Feliz / Contente", phonetic: "/ˈhæp.i/", example: "I am so happy to see you.", examplePt: "Estou tão feliz em ver você." },
  { id: 302, word: "SAD", tip: "Triste", phonetic: "/sæd/", example: "She felt sad after hearing the news.", examplePt: "Ela se sentiu triste depois de ouvir as notícias." },
  { id: 303, word: "ANGRY", tip: "Bravo / Irritado", phonetic: "/ˈæŋ.ɡri/", example: "Take a deep breath and do not get angry.", examplePt: "Respire fundo e não fique bravo." },
  { id: 304, word: "TIRED", tip: "Cansado", phonetic: "/taɪərd/", example: "I am tired after a long day at work.", examplePt: "Estou cansado após um longo dia de trabalho." },
  { id: 305, word: "EXCITED", tip: "Empolgado / Animado", phonetic: "/ɪkˈsaɪ.t̬ɪd/", example: "We are excited about our upcoming trip.", examplePt: "Estamos empolgados com nossa próxima viagem." },
  { id: 306, word: "NERVOUS", tip: "Nervoso / Ansioso", phonetic: "/ˈnɝː.vəs/", example: "He felt nervous before the presentation.", examplePt: "Ele se sentiu nervoso antes da apresentação." },
  { id: 307, word: "CONFIDENT", tip: "Confiante", phonetic: "/ˈkɑːn.fə.dənt/", example: "Speak with a confident and clear voice.", examplePt: "Fale com uma voz confiante e clara." },
  { id: 308, word: "PROUD", tip: "Orgulhoso", phonetic: "/praʊd/", example: "Your parents are very proud of you.", examplePt: "Seus pais estão muito orgulhosos de você." },
  { id: 309, word: "AFRAID", tip: "Com medo / Assustado", phonetic: "/əˈfreɪd/", example: "Do not be afraid of making mistakes.", examplePt: "Não tenha medo de cometer erros." },
  { id: 310, word: "BRAVE", tip: "Corajoso", phonetic: "/breɪv/", example: "The firefighter was exceptionally brave.", examplePt: "O bombeiro foi excepcionalmente corajoso." },
  { id: 311, word: "CALM", tip: "Calmo / Tranquilo", phonetic: "/kɑːm/", example: "Stay calm in stressful situations.", examplePt: "Mantenha a calma em situações estressantes." },
  { id: 312, word: "SURPRISED", tip: "Surpreso", phonetic: "/sɚˈpraɪzd/", example: "I was surprised by the unexpected gift.", examplePt: "Fiquei surpreso com o presente inesperado." },
  { id: 313, word: "BORED", tip: "Entediado", phonetic: "/bɔːrd/", example: "He got bored watching the long movie.", examplePt: "Ele ficou entediado assistindo ao filme longo." },
  { id: 314, word: "CURIOUS", tip: "Curioso", phonetic: "/ˈkjʊr.i.əs/", example: "Children are naturally curious about the world.", examplePt: "As crianças são naturalmente curiosas sobre o mundo." },
  { id: 315, word: "GRATEFUL", tip: "Grato / Agradecido", phonetic: "/ˈɡreɪt.fəl/", example: "I am grateful for your kind help.", examplePt: "Sou grato pela sua ajuda gentil." },
  { id: 316, word: "JEALOUS", tip: "Com ciúmes / Invejoso", phonetic: "/ˈdʒel.əs/", example: "Try not to feel jealous of others.", examplePt: "Tente não sentir inveja dos outros." },
  { id: 317, word: "LONELY", tip: "Solitário", phonetic: "/ˈloʊn.li/", example: "He felt lonely living in a big new city.", examplePt: "Ele se sentiu solitário morando em uma cidade grande nova." },
  { id: 318, word: "HOPEFUL", tip: "Esperançoso", phonetic: "/ˈhoʊp.fəl/", example: "We are hopeful for a brighter future.", examplePt: "Estamos esperançosos por um futuro melhor." },
  { id: 319, word: "PATIENT", tip: "Paciente", phonetic: "/ˈpeɪ.ʃənt/", example: "Learning a language requires being patient.", examplePt: "Aprender um idioma exige ser paciente." },
  { id: 320, word: "KIND", tip: "Gentil / Bondoso", phonetic: "/kaɪnd/", example: "Always be kind to everyone you meet.", examplePt: "Seja sempre gentil com todos que você encontrar." },
  { id: 321, word: "HONEST", tip: "Honesto / Sincero", phonetic: "/ˈɑː.nɪst/", example: "She gave an honest answer.", examplePt: "Ela deu uma resposta sincera." },
  { id: 322, word: "FRIENDLY", tip: "Amigável / Simpático", phonetic: "/ˈfrend.li/", example: "The locals were friendly and welcoming.", examplePt: "Os habitantes locais foram amigáveis e acolhedores." },
  { id: 323, word: "SHY", tip: "Tímido", phonetic: "/ʃaɪ/", example: "He is a bit shy when meeting new people.", examplePt: "Ele é um pouco tímido ao conhecer pessoas novas." },
  { id: 324, word: "GENEROUS", tip: "Generoso", phonetic: "/ˈdʒen.ər.əs/", example: "Thank you for your generous support.", examplePt: "Obrigado pelo seu apoio generoso." },
  { id: 325, word: "LAZY", tip: "Preguiçoso", phonetic: "/ˈleɪ.zi/", example: "Do not be lazy on Monday morning.", examplePt: "Não tenha preguiça na manhã de segunda-feira." },
  { id: 326, word: "POLITE", tip: "Educado / Cortês", phonetic: "/pəˈlaɪt/", example: "Saying thank you is very polite.", examplePt: "Dizer obrigado é muito educado." },
  { id: 327, word: "CREATIVE", tip: "Criativo", phonetic: "/kriˈeɪ.t̬ɪv/", example: "She has many creative ideas.", examplePt: "Ela tem muitas ideias criativas." },
  { id: 328, word: "SMART", tip: "Inteligente / Esperto", phonetic: "/smɑːrt/", example: "That was a very smart decision.", examplePt: "Essa foi uma decisão muito inteligente." },
  { id: 329, word: "FUNNY", tip: "Engraçado", phonetic: "/ˈfʌn.i/", example: "He told a funny joke at the party.", examplePt: "Ele contou uma piada engraçada na festa." },
  { id: 330, word: "SERIOUS", tip: "Sério", phonetic: "/ˈsɪr.i.əs/", example: "Learning English is a serious goal.", examplePt: "Aprender inglês é uma meta séria." },
  { id: 331, word: "WORRIED", tip: "Preocupado", phonetic: "/ˈwɝː.id/", example: "Do not be worried; everything is fine.", examplePt: "Não fique preocupado; tudo está bem." },
  { id: 332, word: "RELAXED", tip: "Relaxado / Tranquilo", phonetic: "/rɪˈlækst/", example: "I feel completely relaxed on weekends.", examplePt: "Eu me sinto completamente relaxado nos fins de semana." },
  { id: 333, word: "EMBARRASSED", tip: "Envergonhado", phonetic: "/ɪmˈber.əst/", example: "He felt embarrassed when he made a mistake.", examplePt: "Ele se sentiu envergonhado quando cometeu um erro." },
  { id: 334, word: "ENTHUSIASTIC", tip: "Entusiasta / Empolgado", phonetic: "/ɪnˌθuː.ziˈæs.tɪk/", example: "She is enthusiastic about her new project.", examplePt: "Ela está entusiasmada com seu novo projeto." },
  { id: 335, word: "DISAPPOINTED", tip: "Decepcionado", phonetic: "/ˌdɪs.əˈpɔɪn.t̬ɪd/", example: "We were disappointed with the canceled flight.", examplePt: "Ficamos decepcionados com o voo cancelado." },
  { id: 336, word: "OPTIMISTIC", tip: "Otimista", phonetic: "/ˌɑːp.təˈmɪs.tɪk/", example: "Keep an optimistic attitude toward life.", examplePt: "Mantenha uma atitude otimista perante a vida." },
  { id: 337, word: "PESSIMISTIC", tip: "Pessimista", phonetic: "/ˌpes.əˈmɪs.tɪk/", example: "Do not be pessimistic about the future.", examplePt: "Não seja pessimista em relação ao futuro." },
  { id: 338, word: "AFFECTIONATE", tip: "Carinhoso / Afetuoso", phonetic: "/əˈfek.ʃən.ət/", example: "The puppy is very affectionate.", examplePt: "O cachorrinho é muito carinhoso." },
  { id: 339, word: "PASSIONATE", tip: "Apaixonado / Dedicado", phonetic: "/ˈpæʃ.ən.ət/", example: "He is passionate about teaching English.", examplePt: "Ele é apaixonado por ensinar inglês." },
  { id: 340, word: "AMBITIOUS", tip: "Ambicioso", phonetic: "/æmˈbɪʃ.əs/", example: "She has ambitious career dreams.", examplePt: "Ela tem sonhos de carreira ambiciosos." },
  { id: 341, word: "STRESSED", tip: "Estressado", phonetic: "/strest/", example: "Take a break when you feel stressed.", examplePt: "Faça uma pausa quando se sentir estressado." },
  { id: 342, word: "PEACEFUL", tip: "Pacífico / Em paz", phonetic: "/ˈpiːs.fəl/", example: "The mountain village is so peaceful.", examplePt: "A vila na montanha é tão pacífica." },
  { id: 343, word: "ENERGETIC", tip: "Enérgico / Disposto", phonetic: "/ˌen.ɚˈdʒet̬.ɪk/", example: "Exercise makes me feel energetic.", examplePt: "Exercícios me fazem sentir com energia." },
  { id: 344, word: "LOVING", tip: "Amoroso / Afetuoso", phonetic: "/ˈlʌv.ɪŋ/", example: "A warm and loving family.", examplePt: "Uma família calorosa e amorosa." },
  { id: 345, word: "FORGIVING", tip: "Perdoador / Tolerante", phonetic: "/fɚˈɡɪv.ɪŋ/", example: "A forgiving heart brings inner peace.", examplePt: "Um coração perdoador traz paz interior." },
  { id: 346, word: "INDEPENDENT", tip: "Independente", phonetic: "/ˌɪn.dɪˈpen.dənt/", example: "She is a confident and independent woman.", examplePt: "Ela é uma mulher confiante e independente." },
  { id: 347, word: "RESPONSIBLE", tip: "Responsável", phonetic: "/rɪˈspɑːn.sə.bəl/", example: "He is a responsible and punctual person.", examplePt: "Ele é uma pessoa responsável e pontual." },
  { id: 348, word: "THANKFUL", tip: "Agradecido / Reconhecido", phonetic: "/ˈθæŋk.fəl/", example: "We are thankful for all our blessings.", examplePt: "Somos agradecidos por todas as nossas bênçãos." },
  { id: 349, word: "DETERMINED", tip: "Determinado", phonetic: "/dɪˈtɝː.mɪnd/", example: "I am determined to become fluent in English.", examplePt: "Estou determinado a ficar fluente em inglês." },
  { id: 350, word: "COURAGEOUS", tip: "Corajoso / Destemido", phonetic: "/kəˈreɪ.dʒəs/", example: "It was a courageous decision to make.", examplePt: "Foi uma decisão corajosa de se tomar." },
]
