import type { Challenge } from "../types"

export const WORDS_BIBLE: Challenge[] = [
  { id: 501, word: "JESUS", tip: "Jesus (Filho de Deus)", phonetic: "/ˈdʒiː.zəs/", example: "Jesus preached love, grace, and forgiveness.", examplePt: "Jesus pregou o amor, a graça e o perdão." },
  { id: 502, word: "MOSES", tip: "Moisés (Líder do Êxodo)", phonetic: "/ˈmoʊ.zɪs/", example: "Moses led the people across the Red Sea.", examplePt: "Moisés liderou o povo através do Mar Vermelho." },
  { id: 503, word: "ABRAHAM", tip: "Abraão (Pai da Fé)", phonetic: "/ˈeɪ.brə.hæm/", example: "Abraham trusted in God's eternal promise.", examplePt: "Abraão confiou na promessa eterna de Deus." },
  { id: 504, word: "DAVID", tip: "Davi (Rei e Salmista)", phonetic: "/ˈdeɪ.vɪd/", example: "David wrote many of the beautiful Psalms.", examplePt: "Davi escreveu muitos dos belos Salmos." },
  { id: 505, word: "SOLOMON", tip: "Salomão (Rei sábio)", phonetic: "/ˈsɑː.lə.mən/", example: "King Solomon was renowned for his great wisdom.", examplePt: "O Rei Salomão era renomado por sua grande sabedoria." },
  { id: 506, word: "NOAH", tip: "Noé (Construiu a arca)", phonetic: "/ˈnoʊ.ə/", example: "Noah built an ark following God's instructions.", examplePt: "Noé construiu uma arca seguindo as instruções de Deus." },
  { id: 507, word: "PETER", tip: "Pedro (Apóstolo)", phonetic: "/ˈpiː.t̬ɚ/", example: "Peter was a faithful apostle and fisherman.", examplePt: "Pedro foi um apóstolo fiel e pescador." },
  { id: 508, word: "PAUL", tip: "Paulo (Apóstolo aos gentios)", phonetic: "/pɑːl/", example: "Paul wrote letters to strengthen early churches.", examplePt: "Paulo escreveu cartas para fortalecer as primeiras igrejas." },
  { id: 509, word: "JOHN", tip: "João (Apóstolo do amor)", phonetic: "/dʒɑːn/", example: "John was known as the beloved disciple.", examplePt: "João era conhecido como o discípulo amado." },
  { id: 510, word: "MARY", tip: "Maria (Mãe de Jesus)", phonetic: "/ˈmer.i/", example: "Mary praised God with a grateful heart.", examplePt: "Maria louvou a Deus com um coração agradecido." },
  { id: 511, word: "JOSEPH", tip: "José (Esposo de Maria / Filho de Jacó)", phonetic: "/ˈdʒoʊ.zəf/", example: "Joseph was an honorable and righteous man.", examplePt: "José era um homem honrado e justo." },
  { id: 512, word: "ELIJAH", tip: "Elias (Profeta de Deus)", phonetic: "/ɪˈlaɪ.dʒə/", example: "Elijah prayed earnestly on Mount Carmel.", examplePt: "Elias orou fervorosamente no Monte Carmelo." },
  { id: 513, word: "DANIEL", tip: "Daniel (Profeta na cova dos leões)", phonetic: "/ˈdæn.jəl/", example: "Daniel remained faithful in Babylon.", examplePt: "Daniel permaneceu fiel na Babilônia." },
  { id: 514, word: "SAMUEL", tip: "Samuel (Profeta e Juiz)", phonetic: "/ˈsæm.ju.əl/", example: "Samuel listened when God called his name.", examplePt: "Samuel ouviu quando Deus chamou seu nome." },
  { id: 515, word: "ISAIAH", tip: "Isaías (Grande profeta messiânico)", phonetic: "/aɪˈzeɪ.ə/", example: "Isaiah prophesied about the Prince of Peace.", examplePt: "Isaías profetizou sobre o Príncipe da Paz." },
  { id: 516, word: "ESTHER", tip: "Ester (Rainha corajosa)", phonetic: "/ˈes.tɚ/", example: "Queen Esther acted bravely to save her people.", examplePt: "A Rainha Ester agiu com bravura para salvar seu povo." },
  { id: 517, word: "RUTH", tip: "Rute (Exemplo de lealdade)", phonetic: "/ruːθ/", example: "Ruth showed unconditional loyalty to Naomi.", examplePt: "Rute demonstrou lealdade incondicional a Noemi." },
  { id: 518, word: "JOSHUA", tip: "Josué (Sucessor de Moisés)", phonetic: "/ˈdʒɑː.ʃu.ə/", example: "Joshua was commanded to be strong and courageous.", examplePt: "Josué foi instruído a ser forte e corajoso." },
  { id: 519, word: "GABRIEL", tip: "Gabriel (Arcanjo mensageiro)", phonetic: "/ˈɡeɪ.bri.əl/", example: "The angel Gabriel brought good news of peace.", examplePt: "O anjo Gabriel trouxe boas notícias de paz." },
  { id: 520, word: "SARAH", tip: "Sara (Esposa de Abraão)", phonetic: "/ˈser.ə/", example: "Sarah was blessed with a son named Isaac.", examplePt: "Sara foi abençoada com um filho chamado Isaque." },
  { id: 521, word: "JACOB", tip: "Jacó (Chamado de Israel)", phonetic: "/ˈdʒeɪ.kəb/", example: "Jacob was the father of the twelve tribes.", examplePt: "Jacó foi o pai das doze tribos." },
  { id: 522, word: "ISAAC", tip: "Isaque (Filho da promessa)", phonetic: "/ˈaɪ.zək/", example: "Isaac lived a life of peace and blessing.", examplePt: "Isaque viveu uma vida de paz e bênção." },
  { id: 523, word: "GIDEON", tip: "Gideão (Guerreiro valoroso)", phonetic: "/ˈɡɪd.i.ən/", example: "Gideon led three hundred brave men.", examplePt: "Gideão liderou trezentos homens corajosos." },
  { id: 524, word: "SAMSON", tip: "Sansão (Homem de grande força)", phonetic: "/ˈsæm.sən/", example: "Samson was granted extraordinary strength.", examplePt: "Sansão recebeu uma força extraordinária." },
  { id: 525, word: "STEPHEN", tip: "Estêvão (Primeiro mártir)", phonetic: "/ˈstiː.vən/", example: "Stephen was a man full of faith and the Holy Spirit.", examplePt: "Estêvão era um homem cheio de fé e do Espírito Santo." },
  { id: 526, word: "LUKE", tip: "Lucas (Médico e Evangelista)", phonetic: "/luːk/", example: "Luke wrote an orderly account of the Gospel.", examplePt: "Lucas escreveu um relato ordenado do Evangelho." },
  { id: 527, word: "MATTHEW", tip: "Mateus (Apóstolo e Evangelista)", phonetic: "/ˈmæθ.juː/", example: "Matthew followed Jesus immediately when called.", examplePt: "Mateus seguiu a Jesus imediatamente quando foi chamado." },
  { id: 528, word: "MARK", tip: "Marcos (Evangelista)", phonetic: "/mɑːrk/", example: "Mark recorded the active ministry of Jesus.", examplePt: "Marcos registrou o ministério ativo de Jesus." },
  { id: 529, word: "TIMOTHY", tip: "Timóteo (Jovem líder e pastor)", phonetic: "/ˈtɪm.ə.θi/", example: "Timothy was mentored by Paul with great care.", examplePt: "Timóteo foi orientado por Paulo com grande carinho." },
  { id: 530, word: "JONAH", tip: "Jonas (Profeta em Nínive)", phonetic: "/ˈdʒoʊ.nə/", example: "Jonah preached repentance to the city of Nineveh.", examplePt: "Jonas pregou o arrependimento à cidade de Nínive." },
  { id: 531, word: "JOB", tip: "Jó (Exemplo de paciência e integridade)", phonetic: "/dʒoʊb/", example: "Job remained faithful through all trials.", examplePt: "Jó permaneceu fiel em meio a todas as provações." },
  { id: 532, word: "NEHEMIAH", tip: "Neemias (Reconstruiu os muros)", phonetic: "/ˌniː.əˈmaɪ.ə/", example: "Nehemiah led the rebuilding of the city walls.", examplePt: "Neemias liderou a reconstrução dos muros da cidade." },
  { id: 533, word: "JERUSALEM", tip: "Jerusalém (Cidade Santa)", phonetic: "/dʒəˈruː.sə.ləm/", example: "Jerusalem is a city rich in biblical history.", examplePt: "Jerusalém é uma cidade rica em história bíblica." },
  { id: 534, word: "BETHLEHEM", tip: "Belém (Cidade onde Jesus nasceu)", phonetic: "/ˈbeθ.lɪ.hem/", example: "Jesus was born in Bethlehem of Judea.", examplePt: "Jesus nasceu em Belém da Judeia." },
  { id: 535, word: "NAZARETH", tip: "Nazaré (Onde Jesus cresceu)", phonetic: "/ˈnæz.ɚ.əθ/", example: "Jesus grew up in the town of Nazareth.", examplePt: "Jesus cresceu na cidade de Nazaré." },
  { id: 536, word: "GALILEE", tip: "Galileia (Região no norte de Israel)", phonetic: "/ˈɡæl.ə.liː/", example: "Jesus performed many miracles around the Sea of Galilee.", examplePt: "Jesus realizou muitos milagres ao redor do Mar da Galileia." },
  { id: 537, word: "JORDAN RIVER", tip: "Rio Jordão (Onde Jesus foi batizado)", phonetic: "/ˈdʒɔːr.dən ˌrɪv.ɚ/", example: "John baptized believers in the Jordan River.", examplePt: "João batizou os crentes no Rio Jordão." },
  { id: 538, word: "EDEN", tip: "Éden (Jardim da Criação)", phonetic: "/ˈiː.dən/", example: "God created the beautiful Garden of Eden.", examplePt: "Deus criou o lindo Jardim do Éden." },
  { id: 539, word: "MOUNT SINAI", tip: "Monte Sinai (Onde Moisés recebeu a Lei)", phonetic: "/ˌmaʊnt ˈsaɪ.naɪ/", example: "Moses met God on top of Mount Sinai.", examplePt: "Moisés se encontrou com Deus no topo do Monte Sinai." },
  { id: 540, word: "JERICHO", tip: "Jericó (Cidade com grandes muralhas)", phonetic: "/ˈdʒer.ɪ.koʊ/", example: "The walls of Jericho fell after Israel marched.", examplePt: "As muralhas de Jericó caíram depois que Israel marchou." },
  { id: 541, word: "BABYLON", tip: "Babilônia (Antigo império bíblico)", phonetic: "/ˈbæb.ə.lɑːn/", example: "The captives longed for home while in Babylon.", examplePt: "Os cativos ansiavam por sua terra natal enquanto estavam na Babilônia." },
  { id: 542, word: "EGYPT", tip: "Egito (Terra dos faraós)", phonetic: "/ˈiː.dʒɪpt/", example: "Joseph became a prominent leader in Egypt.", examplePt: "José se tornou um líder proeminente no Egito." },
  { id: 543, word: "CANAAN", tip: "Canaã (A Terra Prometida)", phonetic: "/ˈkeɪ.nən/", example: "Canaan was the land promised to Abraham's descendants.", examplePt: "Canaã era a terra prometida aos descendentes de Abraão." },
  { id: 544, word: "DAMASCUS", tip: "Damasco (Onde Paulo teve seu encontro com Cristo)", phonetic: "/dəˈmæs.kəs/", example: "Paul experienced a life-changing vision on the road to Damascus.", examplePt: "Paulo teve uma visão transformadora na estrada para Damasco." },
  { id: 545, word: "RED SEA", tip: "Mar Vermelho (Águas divididas por Deus)", phonetic: "/ˌred ˈsiː/", example: "God parted the waters of the Red Sea.", examplePt: "Deus abriu as águas do Mar Vermelho." },
  { id: 546, word: "MOUNT OLIVES", tip: "Monte das Oliveiras (Lugar de oração)", phonetic: "/ˌmaʊnt ˈɑː.lɪvz/", example: "Jesus often prayed on the Mount of Olives.", examplePt: "Jesus orava frequentemente no Monte das Oliveiras." },
  { id: 547, word: "BETHEL", tip: "Betel (Casa de Deus)", phonetic: "/ˈbeθ.əl/", example: "Jacob set up a stone pillar at Bethel.", examplePt: "Jacó levantou uma coluna de pedra em Betel." },
  { id: 548, word: "HEBRON", tip: "Hebrom (Cidade histórica dos patriarcas)", phonetic: "/ˈhiː.brən/", example: "Hebron was an ancient and important city.", examplePt: "Hebrom era uma cidade antiga e importante." },
  { id: 549, word: "CORINTH", tip: "Corinto (Cidade para onde Paulo escreveu cartas)", phonetic: "/ˈkɔːr.ɪnθ/", example: "Paul established a church in the city of Corinth.", examplePt: "Paulo estabeleceu uma igreja na cidade de Corinto." },
  { id: 550, word: "ROME", tip: "Roma (Capital do Império e ministério de Paulo)", phonetic: "/roʊm/", example: "Paul preached the Gospel boldly in Rome.", examplePt: "Paulo pregou o Evangelho com ousadia em Roma." },
]
