export type Challenge = {
  id: number
  word: string
  tip: string
}

export const WORDS_DAILY: Challenge[] = [
  { id: 1, word: "HOUSE", tip: "Casa" },
  { id: 2, word: "ROOM", tip: "Quarto" },
  { id: 3, word: "KITCHEN", tip: "Cozinha" },
  { id: 4, word: "BATHROOM", tip: "Banheiro" },
  { id: 5, word: "WINDOW", tip: "Janela" },
  { id: 6, word: "DOOR", tip: "Porta" },
  { id: 7, word: "BED", tip: "Cama" },
  { id: 8, word: "TABLE", tip: "Mesa" },
  { id: 9, word: "CHAIR", tip: "Cadeira" },
  { id: 10, word: "LIGHT", tip: "Luz" },
  { id: 11, word: "FOOD", tip: "Comida" },
  { id: 12, word: "FRIDGE", tip: "Geladeira" },
  { id: 13, word: "WATER", tip: "Água" },
  { id: 14, word: "BREAD", tip: "Pão" },
  { id: 15, word: "COFFEE", tip: "Café" },
  { id: 16, word: "MILK", tip: "Leite" },
  { id: 17, word: "SUGAR", tip: "Açúcar" },
  { id: 18, word: "FRUIT", tip: "Fruta" },
  { id: 19, word: "CLOTHES", tip: "Roupas" },
  { id: 20, word: "SHOES", tip: "Sapatos" },
  { id: 21, word: "PHONE", tip: "Telefone / Celular" },
  { id: 22, word: "KEYS", tip: "Chaves" },
  { id: 23, word: "WALL", tip: "Parede" },
  { id: 24, word: "FLOOR", tip: "Chão / Piso" },
  { id: 25, word: "CLOCK", tip: "Relógio" },
  { id: 26, word: "TV", tip: "Televisão" },
  { id: 27, word: "COMPUTER", tip: "Computador" },
  { id: 28, word: "BAG", tip: "Bolsa / Mochila" },
  { id: 29, word: "SOAP", tip: "Sabão / Sabonete" },
  { id: 30, word: "TOWEL", tip: "Toalha" },
  { id: 31, word: "MIRROR", tip: "Espelho" },
  { id: 32, word: "BRUSH", tip: "Escova" },
  { id: 33, word: "TOOTHPASTE", tip: "Creme dental" },
  { id: 34, word: "SHOWER", tip: "Chuveiro" },
  { id: 35, word: "CAR", tip: "Carro" },
  { id: 36, word: "BUS", tip: "Ônibus" },
  { id: 37, word: "STREET", tip: "Rua" },
  { id: 38, word: "SHOP", tip: "Loja" },
  { id: 39, word: "SUPERMARKET", tip: "Supermercado" },
  { id: 40, word: "MONEY", tip: "Dinheiro" },
  { id: 41, word: "PEN", tip: "Caneta" },
  { id: 42, word: "BOOK", tip: "Livro" },
  { id: 43, word: "NEWSPAPER", tip: "Jornal" },
  { id: 44, word: "PAPER", tip: "Papel" },
  { id: 45, word: "HAND", tip: "Mão" },
  { id: 46, word: "HEAD", tip: "Cabeça" },
  { id: 47, word: "FACE", tip: "Rosto" },
  { id: 48, word: "EYES", tip: "Olhos" },
  { id: 49, word: "HAIR", tip: "Cabelo" },
  { id: 50, word: "FAMILY", tip: "Família" },
]


