export type Challenge = {
  id: number
  word: string
  tip: string
}

export const WORDS_WORK: Challenge[] = [
  { id: 1, word: "JOB", tip: "Emprego" },
  { id: 2, word: "WORK", tip: "Trabalho" },
  { id: 3, word: "OFFICE", tip: "Escritório" },
  { id: 4, word: "MEETING", tip: "Reunião" },
  { id: 5, word: "BOSS", tip: "Chefe" },
  { id: 6, word: "COLLEAGUE", tip: "Colega de trabalho" },
  { id: 7, word: "SALARY", tip: "Salário" },
  { id: 8, word: "CAREER", tip: "Carreira" },
  { id: 9, word: "PROJECT", tip: "Projeto" },
  { id: 10, word: "DEADLINE", tip: "Prazo final" },
  { id: 11, word: "MEETING ROOM", tip: "Sala de reunião" },
  { id: 12, word: "EMAIL", tip: "Correio eletrônico" },
  { id: 13, word: "REPORT", tip: "Relatório" },
  { id: 14, word: "PRESENTATION", tip: "Apresentação" },
  { id: 15, word: "CLIENT", tip: "Cliente" },
  { id: 16, word: "MANAGER", tip: "Gerente" },
  { id: 17, word: "EMPLOYEE", tip: "Empregado / Funcionário" },
  { id: 18, word: "INTERVIEW", tip: "Entrevista" },
  { id: 19, word: "CONTRACT", tip: "Contrato" },
  { id: 20, word: "COMPANY", tip: "Empresa" },
  { id: 21, word: "TEAM", tip: "Equipe / Time" },
  { id: 22, word: "TASK", tip: "Tarefa" },
  { id: 23, word: "SCHEDULE", tip: "Agenda / Cronograma" },
  { id: 24, word: "DEPARTMENT", tip: "Departamento / Setor" },
  { id: 25, word: "MEETING MINUTES", tip: "Ata da reunião" },
  { id: 26, word: "DOCUMENT", tip: "Documento" },
  { id: 27, word: "PRINTER", tip: "Impressora" },
  { id: 28, word: "DESK", tip: "Mesa de trabalho" },
  { id: 29, word: "COMPUTER", tip: "Computador" },
  { id: 30, word: "INTERNET", tip: "Internet" },
  { id: 31, word: "PROJECT MANAGER", tip: "Gerente de projeto" },
  { id: 32, word: "MEETING AGENDA", tip: "Pauta da reunião" },
  { id: 33, word: "SALARY INCREASE", tip: "Aumento de salário" },
  { id: 34, word: "PROMOTION", tip: "Promoção" },
  { id: 35, word: "TRAINING", tip: "Treinamento" },
  { id: 36, word: "HARDWORKING", tip: "Trabalhador / Dedicado" },
  { id: 37, word: "DEADLINE EXTENSION", tip: "Extensão do prazo" },
  { id: 38, word: "WORKPLACE", tip: "Local de trabalho" },
  { id: 39, word: "MEETING CALL", tip: "Chamada de reunião" },
  { id: 40, word: "JOB OFFER", tip: "Oferta de emprego" },
  { id: 41, word: "APPLICATION", tip: "Candidatura" },
  { id: 42, word: "RESUME", tip: "Currículo" },
  { id: 43, word: "VACATION", tip: "Férias" },
  { id: 44, word: "BUSINESS TRIP", tip: "Viagem de negócios" },
  { id: 45, word: "WORK HOURS", tip: "Horário de trabalho" },
  { id: 46, word: "OVERTIME", tip: "Hora extra" },
  { id: 47, word: "RESPONSIBILITY", tip: "Responsabilidade" },
  { id: 48, word: "MEETING NOTES", tip: "Anotações da reunião" },
  { id: 49, word: "JOB POSITION", tip: "Cargo" },
  { id: 50, word: "PERFORMANCE", tip: "Desempenho" },
]
