import type { Challenge } from "../types"

export const WORDS_WORK: Challenge[] = [
  { id: 201, word: "JOB", tip: "Emprego / Trabalho", phonetic: "/dʒɑːb/", example: "She applied for a new job.", examplePt: "Ela se candidatou para um novo emprego." },
  { id: 202, word: "WORK", tip: "Trabalho", phonetic: "/wɜːrk/", example: "I have a lot of work to finish.", examplePt: "Tenho muito trabalho para terminar." },
  { id: 203, word: "OFFICE", tip: "Escritório", phonetic: "/ˈɑː.fɪs/", example: "Our office is on the fifth floor.", examplePt: "Nosso escritório fica no quinto andar." },
  { id: 204, word: "MEETING", tip: "Reunião", phonetic: "/ˈmiː.tɪŋ/", example: "The meeting starts at 10 AM.", examplePt: "A reunião começa às 10h." },
  { id: 205, word: "BOSS", tip: "Chefe", phonetic: "/bɑːs/", example: "Talk to your boss about the idea.", examplePt: "Converse com seu chefe sobre a ideia." },
  { id: 206, word: "COLLEAGUE", tip: "Colega de trabalho", phonetic: "/ˈkɑː.liːɡ/", example: "He is a helpful colleague.", examplePt: "Ele é um colega de trabalho prestativo." },
  { id: 207, word: "SALARY", tip: "Salário", phonetic: "/ˈsæl.ɚ.i/", example: "Salaries are paid at the end of the month.", examplePt: "Os salários são pagos no fim do mês." },
  { id: 208, word: "CAREER", tip: "Carreira", phonetic: "/kəˈrɪr/", example: "She has built a successful career.", examplePt: "Ela construiu uma carreira de sucesso." },
  { id: 209, word: "PROJECT", tip: "Projeto", phonetic: "/ˈprɑː.dʒekt/", example: "We launched the new project yesterday.", examplePt: "Lançamos o novo projeto ontem." },
  { id: 210, word: "DEADLINE", tip: "Prazo final", phonetic: "/ˈded.laɪn/", example: "The project deadline is this Friday.", examplePt: "O prazo do projeto é nesta sexta-feira." },
  { id: 211, word: "MEETING ROOM", tip: "Sala de reunião", phonetic: "/ˈmiː.tɪŋ ruːm/", example: "Let's gather in the meeting room.", examplePt: "Vamos nos reunir na sala de reunião." },
  { id: 212, word: "EMAIL", tip: "Correio eletrônico / E-mail", phonetic: "/ˈiː.meɪl/", example: "I will send you a confirmation email.", examplePt: "Vou te enviar um e-mail de confirmação." },
  { id: 213, word: "REPORT", tip: "Relatório", phonetic: "/rɪˈpɔːrt/", example: "Please send me the weekly sales report.", examplePt: "Por favor, me envie o relatório semanal de vendas." },
  { id: 214, word: "PRESENTATION", tip: "Apresentação", phonetic: "/ˌprez.ənˈteɪ.ʃən/", example: "His slide presentation was clear.", examplePt: "A apresentação de slides dele foi clara." },
  { id: 215, word: "CLIENT", tip: "Cliente", phonetic: "/ˈklaɪ.ənt/", example: "The client approved the proposal.", examplePt: "O cliente aprovou a proposta." },
  { id: 216, word: "MANAGER", tip: "Gerente", phonetic: "/ˈmæn.ə.dʒɚ/", example: "The project manager approved the budget.", examplePt: "O gerente de projetos aprovou o orçamento." },
  { id: 217, word: "EMPLOYEE", tip: "Empregado / Funcionário", phonetic: "/ɪmˈplɔɪ.iː/", example: "Every employee receives full training.", examplePt: "Cada funcionário recebe treinamento completo." },
  { id: 218, word: "INTERVIEW", tip: "Entrevista", phonetic: "/ˈɪn.t̬ɚ.vjuː/", example: "She did very well in her job interview.", examplePt: "Ela foi muito bem na entrevista de emprego." },
  { id: 219, word: "CONTRACT", tip: "Contrato", phonetic: "/ˈkɑːn.trækt/", example: "Sign the contract on the last page.", examplePt: "Assine o contrato na última página." },
  { id: 220, word: "COMPANY", tip: "Empresa", phonetic: "/ˈkʌm.pə.ni/", example: "This tech company is growing fast.", examplePt: "Esta empresa de tecnologia está crescendo rápido." },
  { id: 221, word: "TEAM", tip: "Equipe / Time", phonetic: "/tiːm/", example: "Teamwork makes the dream work.", examplePt: "O trabalho em equipe faz o sonho acontecer." },
  { id: 222, word: "TASK", tip: "Tarefa", phonetic: "/tæsk/", example: "Complete this task before leaving.", examplePt: "Conclua esta tarefa antes de sair." },
  { id: 223, word: "SCHEDULE", tip: "Agenda / Cronograma", phonetic: "/ˈskedʒ.uːl/", example: "Check your work schedule for next week.", examplePt: "Confira sua escala de trabalho para a próxima semana." },
  { id: 224, word: "DEPARTMENT", tip: "Departamento / Setor", phonetic: "/dɪˈpɑːrt.mənt/", example: "Contact the human resources department.", examplePt: "Contate o departamento de recursos humanos." },
  { id: 225, word: "MEETING MINUTES", tip: "Ata da reunião", phonetic: "/ˈmiː.tɪŋ ˌmɪn.ɪts/", example: "I will email the meeting minutes to everyone.", examplePt: "Vou enviar a ata da reunião para todos por e-mail." },
  { id: 226, word: "DOCUMENT", tip: "Documento", phonetic: "/ˈdɑː.kjə.mənt/", example: "Save the document in the shared cloud folder.", examplePt: "Salve o documento na pasta compartilhada na nuvem." },
  { id: 227, word: "PRINTER", tip: "Impressora", phonetic: "/ˈprɪn.t̬ɚ/", example: "The office printer needs more paper.", examplePt: "A impressora do escritório precisa de mais papel." },
  { id: 228, word: "DESK", tip: "Mesa de trabalho", phonetic: "/desk/", example: "Keep your desk clean and organized.", examplePt: "Mantenha sua mesa de trabalho limpa e organizada." },
  { id: 229, word: "COMPUTER", tip: "Computador", phonetic: "/kəmˈpjuː.t̬ɚ/", example: "Restart your computer after updates.", examplePt: "Reinicie seu computador após as atualizações." },
  { id: 230, word: "INTERNET", tip: "Internet", phonetic: "/ˈɪn.t̬ɚ.net/", example: "We have high-speed internet access here.", examplePt: "Temos acesso à internet de alta velocidade aqui." },
  { id: 231, word: "PROJECT MANAGER", tip: "Gerente de projeto", phonetic: "/ˈprɑː.dʒekt ˌmæn.ə.dʒɚ/", example: "The project manager leads daily standups.", examplePt: "O gerente de projetos lidera os alinhamentos diários." },
  { id: 232, word: "MEETING AGENDA", tip: "Pauta da reunião", phonetic: "/ˈmiː.tɪŋ əˌdʒen.də/", example: "Please review the meeting agenda in advance.", examplePt: "Por favor, revise a pauta da reunião com antecedência." },
  { id: 233, word: "SALARY INCREASE", tip: "Aumento de salário", phonetic: "/ˈsæl.ɚ.i ˌɪn.kriːs/", example: "He requested a well-deserved salary increase.", examplePt: "Ele solicitou um merecido aumento de salário." },
  { id: 234, word: "PROMOTION", tip: "Promoção", phonetic: "/prəˈmoʊ.ʃən/", example: "She received a promotion to director.", examplePt: "Ela recebeu uma promoção para diretora." },
  { id: 235, word: "TRAINING", tip: "Treinamento", phonetic: "/ˈtreɪ.nɪŋ/", example: "New employees start training next week.", examplePt: "Os novos funcionários começam o treinamento na próxima semana." },
  { id: 236, word: "HARDWORKING", tip: "Trabalhador / Dedicado", phonetic: "/ˌhɑːrdˈwɝː.kɪŋ/", example: "He is a very hardworking professional.", examplePt: "Ele é um profissional muito dedicado." },
  { id: 237, word: "DEADLINE EXTENSION", tip: "Extensão do prazo", phonetic: "/ˈded.laɪn ɪkˌsten.ʃən/", example: "We asked for a short deadline extension.", examplePt: "Pedimos uma pequena extensão do prazo." },
  { id: 238, word: "WORKPLACE", tip: "Local de trabalho", phonetic: "/ˈwɝːk.pleɪs/", example: "A positive workplace culture increases productivity.", examplePt: "Uma cultura de trabalho positiva aumenta a produtividade." },
  { id: 239, word: "MEETING CALL", tip: "Chamada de reunião", phonetic: "/ˈmiː.tɪŋ kɔːl/", example: "Join the video meeting call at 2 PM.", examplePt: "Entre na chamada de reunião em vídeo às 14h." },
  { id: 240, word: "JOB OFFER", tip: "Oferta de emprego", phonetic: "/ˈdʒɑːb ˌɑː.fɚ/", example: "He accepted the attractive job offer.", examplePt: "Ele aceitou a excelente oferta de emprego." },
  { id: 241, word: "APPLICATION", tip: "Candidatura", phonetic: "/ˌæp.ləˈkeɪ.ʃən/", example: "Submit your online application today.", examplePt: "Envie sua candidatura online hoje." },
  { id: 242, word: "RESUME", tip: "Currículo", phonetic: "/ˈrez.ə.meɪ/", example: "Update your resume with your latest skills.", examplePt: "Atualize seu currículo com suas habilidades mais recentes." },
  { id: 243, word: "VACATION", tip: "Férias", phonetic: "/veɪˈkeɪ.ʃən/", example: "I am taking two weeks of paid vacation.", examplePt: "Vou tirar duas semanas de férias remuneradas." },
  { id: 244, word: "BUSINESS TRIP", tip: "Viagem de negócios", phonetic: "/ˈbɪz.nɪs trɪp/", example: "He traveled to Chicago for a business trip.", examplePt: "Ele viajou para Chicago para uma viagem de negócios." },
  { id: 245, word: "WORK HOURS", tip: "Horário de trabalho", phonetic: "/ˈwɝːk ˌaʊ.ɚz/", example: "Our standard work hours are flexible.", examplePt: "Nosso horário padrão de trabalho é flexível." },
  { id: 246, word: "OVERTIME", tip: "Hora extra", phonetic: "/ˈoʊ.vɚ.taɪm/", example: "He was paid overtime for working Saturday.", examplePt: "Ele recebeu hora extra por trabalhar no sábado." },
  { id: 247, word: "RESPONSIBILITY", tip: "Responsabilidade", phonetic: "/rɪˌspɑːn.səˈbɪl.ə.t̬i/", example: "Taking responsibility leads to professional growth.", examplePt: "Assumir responsabilidade leva ao crescimento profissional." },
  { id: 248, word: "MEETING NOTES", tip: "Anotações da reunião", phonetic: "/ˈmiː.tɪŋ noʊts/", example: "I will summarize the meeting notes for you.", examplePt: "Vou resumir as anotações da reunião para você." },
  { id: 249, word: "JOB POSITION", tip: "Cargo / Posição de trabalho", phonetic: "/ˈdʒɑːb pəˌzɪʃ.ən/", example: "This job position requires fluent English.", examplePt: "Este cargo exige inglês fluente." },
  { id: 250, word: "PERFORMANCE", tip: "Desempenho", phonetic: "/pɚˈfɔːr.məns/", example: "The team achieved outstanding performance.", examplePt: "A equipe alcançou um desempenho excepcional." },
]
