import type { Challenge } from "../types"

export const WORDS_CONNECTORS: Challenge[] = [
  { id: 551, word: "HOWEVER", tip: "No entanto / Porém", phonetic: "/haʊˈev.ɚ/", example: "It was raining; however, we went for a walk.", examplePt: "Estava chovendo; no entanto, nós fomos caminhar." },
  { id: 552, word: "ALTHOUGH", tip: "Embora / Apesar de que", phonetic: "/ɑːlˈðoʊ/", example: "Although he was tired, he finished studying.", examplePt: "Embora estivesse cansado, ele terminou de estudar." },
  { id: 553, word: "THEREFORE", tip: "Portanto / Por isso", phonetic: "/ˈðer.fɔːr/", example: "I practiced daily; therefore, I improved fast.", examplePt: "Pratiquei diariamente; portanto, melhorei rápido." },
  { id: 554, word: "MOREOVER", tip: "Além disso / Ademais", phonetic: "/mɔːrˈoʊ.vɚ/", example: "The book is interesting; moreover, it is cheap.", examplePt: "O livro é interessante; além disso, é barato." },
  { id: 555, word: "FURTHERMORE", tip: "Além do mais / Além de tudo", phonetic: "/ˈfɝː.ðɚ.mɔːr/", example: "He is talented; furthermore, he is hardworking.", examplePt: "Ele é talentoso; além do mais, é muito dedicado." },
  { id: 556, word: "BESIDES", tip: "Além de / Além disso", phonetic: "/bɪˈsaɪdz/", example: "Besides English, she speaks fluent Spanish.", examplePt: "Além do inglês, ela fala espanhol fluente." },
  { id: 557, word: "IN ADDITION", tip: "Adicionalmente / Além disso", phonetic: "/ɪn əˈdɪʃ.ən/", example: "In addition to vocabulary, learn pronunciation.", examplePt: "Além do vocabulário, aprenda pronúncia." },
  { id: 558, word: "ON THE OTHER HAND", tip: "Por outro lado", phonetic: "/ɑːn ðə ˈʌð.ɚ hænd/", example: "Cars are fast; on the other hand, bikes are eco-friendly.", examplePt: "Carros são rápidos; por outro lado, bicicletas não poluem." },
  { id: 559, word: "MEANWHILE", tip: "Enquanto isso / Ao mesmo tempo", phonetic: "/ˈmiːn.waɪl/", example: "Cook the rice; meanwhile, prepare the salad.", examplePt: "Cozinhe o arroz; enquanto isso, prepare a salada." },
  { id: 560, word: "NEVERTHELESS", tip: "Não obstante / Mesmo assim", phonetic: "/ˌnev.ɚ.ðəˈles/", example: "It was difficult; nevertheless, we succeeded.", examplePt: "Foi difícil; mesmo assim, tivemos sucesso." },
  { id: 561, word: "CONSEQUENTLY", tip: "Consequentemente / Como resultado", phonetic: "/ˈkɑːn.sə.kwənt.li/", example: "He studied hard; consequently, he passed.", examplePt: "Ele estudou muito; consequentemente, foi aprovado." },
  { id: 562, word: "IN FACT", tip: "De fato / Na verdade", phonetic: "/ɪn fækt/", example: "In fact, English is easier than you think.", examplePt: "De fato, inglês é mais fácil do que você pensa." },
  { id: 563, word: "ACTUALLY", tip: "Na verdade / Realmente", phonetic: "/ˈæk.tʃu.ə.li/", example: "Actually, I prefer drinking tea over coffee.", examplePt: "Na verdade, prefiro tomar chá em vez de café." },
  { id: 564, word: "BASICALLY", tip: "Basicamente", phonetic: "/ˈbeɪ.sɪ.kəl.i/", example: "Basically, consistency is the key to fluency.", examplePt: "Basicamente, consistência é o segredo da fluência." },
  { id: 565, word: "ESPECIALLY", tip: "Especialmente / Principalmente", phonetic: "/ɪˈspeʃ.əl.i/", example: "I love fruits, especially strawberries.", examplePt: "Eu adoro frutas, especialmente morangos." },
  { id: 566, word: "PARTICULARLY", tip: "Particularmente / Em especial", phonetic: "/pɚˈtɪk.jə.lɚ.li/", example: "She is particularly interested in literature.", examplePt: "Ela é particularmente interessada em literatura." },
  { id: 567, word: "FOR INSTANCE", tip: "Por exemplo", phonetic: "/fɔːr ˈɪn.stəns/", example: "Many animals hibernate, bears for instance.", examplePt: "Muitos animais hibernam, ursos por exemplo." },
  { id: 568, word: "SUCH AS", tip: "Tais como / Como", phonetic: "/sʌtʃ æz/", example: "Citrus fruits such as oranges are rich in vitamin C.", examplePt: "Frutas cítricas como laranjas são ricas em vitamina C." },
  { id: 569, word: "IN ORDER TO", tip: "A fim de / Para", phonetic: "/ɪn ˈɔːr.dɚ tuː/", example: "Practice daily in order to speak with confidence.", examplePt: "Pratique diariamente a fim de falar com confiança." },
  { id: 570, word: "SO THAT", tip: "De modo que / Para que", phonetic: "/soʊ ðæt/", example: "Speak slowly so that everyone understands.", examplePt: "Fale devagar para que todos compreendam." },
  { id: 571, word: "DUE TO", tip: "Devido a / Por causa de", phonetic: "/duː tuː/", example: "The flight was delayed due to heavy fog.", examplePt: "O voo atrasou devido à forte neblina." },
  { id: 572, word: "BECAUSE OF", tip: "Por causa de", phonetic: "/bɪˈkɑːz əv/", example: "We stayed home because of the cold rain.", examplePt: "Ficamos em casa por causa da chuva fria." },
  { id: 573, word: "SINCE", tip: "Visto que / Já que / Desde", phonetic: "/sɪns/", example: "Since it is sunny, let's go to the park.", examplePt: "Já que está ensolarado, vamos ao parque." },
  { id: 574, word: "UNLESS", tip: "A menos que / A não ser que", phonetic: "/ʌnˈles/", example: "You will not learn unless you practice speaking.", examplePt: "Você não aprenderá a menos que pratique a fala." },
  { id: 575, word: "WHETHER", tip: "Se (indicando alternativa)", phonetic: "/ˈweð.ɚ/", example: "I do not know whether it will rain or not.", examplePt: "Não sei se vai chover ou não." },
  { id: 576, word: "EVEN THOUGH", tip: "Mesmo que / Ainda que", phonetic: "/ˈiː.vən ðoʊ/", example: "Even though it was late, he kept reading.", examplePt: "Mesmo que fosse tarde, ele continuou lendo." },
  { id: 577, word: "DESPITE", tip: "Apesar de", phonetic: "/dɪˈspaɪt/", example: "Despite the noise, the baby slept soundly.", examplePt: "Apesar do barulho, o bebê dormiu profundamente." },
  { id: 578, word: "IN SPITE OF", tip: "Apesar de / A despeito de", phonetic: "/ɪn spaɪt əv/", example: "In spite of difficulties, they achieved their dream.", examplePt: "Apesar das dificuldades, eles alcançaram seu sonho." },
  { id: 579, word: "AS WELL AS", tip: "Bem como / Assim como", phonetic: "/æz wel æz/", example: "She speaks French as well as English.", examplePt: "Ela fala francês bem como inglês." },
  { id: 580, word: "NOT ONLY BUT ALSO", tip: "Não apenas, mas também", phonetic: "/nɑːt ˈoʊn.li bʌt ˈɑːl.soʊ/", example: "He is not only smart but also generous.", examplePt: "Ele é não apenas inteligente, mas também generoso." },
  { id: 581, word: "EITHER OR", tip: "Ou... ou (um dos dois)", phonetic: "/ˈiː.ðɚ ɔːr/", example: "You can choose either coffee or hot tea.", examplePt: "Você pode escolher ou café ou chá quente." },
  { id: 582, word: "NEITHER NOR", tip: "Nem... nem (nenhum dos dois)", phonetic: "/ˈniː.ðɚ nɔːr/", example: "Neither John nor Peter knew the answer.", examplePt: "Nem John nem Peter sabiam a resposta." },
  { id: 583, word: "AS SOON AS", tip: "Assim que / Logo que", phonetic: "/æz suːn æz/", example: "Call me as soon as you arrive at the airport.", examplePt: "Ligue-me assim que você chegar ao aeroporto." },
  { id: 584, word: "UNTIL", tip: "Até / Até que", phonetic: "/ʌnˈtɪl/", example: "Wait right here until I return.", examplePt: "Espere aqui mesmo até que eu volte." },
  { id: 585, word: "WHILE", tip: "Enquanto", phonetic: "/waɪl/", example: "Listen to English podcasts while walking.", examplePt: "Ouça podcasts em inglês enquanto caminha." },
  { id: 586, word: "WHEREAS", tip: "Ao passo que / Enquanto que", phonetic: "/werˈæz/", example: "He likes sweet food, whereas I prefer salty.", examplePt: "Ele gosta de comida doce, ao passo que eu prefiro salgada." },
  { id: 587, word: "INSTEAD OF", tip: "Em vez de / Ao invés de", phonetic: "/ɪnˈsted əv/", example: "Drink water instead of sugary soda.", examplePt: "Beba água em vez de refrigerante açucarado." },
  { id: 588, word: "RATHER THAN", tip: "Em vez de / De preferência a", phonetic: "/ˈræð.ɚ ðæn/", example: "I prefer reading books rather than watching TV.", examplePt: "Prefiro ler livros em vez de assistir TV." },
  { id: 589, word: "AS A RESULT", tip: "Como resultado", phonetic: "/æz ə rɪˈzʌlt/", example: "He trained hard; as a result, he won the race.", examplePt: "Ele treinou duro; como resultado, venceu a corrida." },
  { id: 590, word: "FOR THIS REASON", tip: "Por esta razão / Por este motivo", phonetic: "/fɔːr ðɪs ˈriː.zən/", example: "English is global; for this reason, it is valuable.", examplePt: "O inglês é global; por este motivo, é muito valioso." },
  { id: 591, word: "IN SUMMARY", tip: "Em resumo / Em suma", phonetic: "/ɪn ˈsʌm.ɚ.i/", example: "In summary, daily practice builds great fluency.", examplePt: "Em resumo, a prática diária constrói grande fluência." },
  { id: 592, word: "TO CONCLUDE", tip: "Para concluir / Em conclusão", phonetic: "/tuː kənˈkluːd/", example: "To conclude, learning languages expands your world.", examplePt: "Para concluir, aprender idiomas expande o seu mundo." },
  { id: 593, word: "EVENTUALLY", tip: "Com o tempo / Mais cedo ou mais tarde", phonetic: "/ɪˈven.tʃu.ə.li/", example: "With patience, you will eventually speak fluently.", examplePt: "Com paciência, com o tempo você falará fluentemente." },
  { id: 594, word: "FINALLY", tip: "Finalmente / Por fim", phonetic: "/ˈfaɪ.nəl.i/", example: "Finally, the weekend has arrived!", examplePt: "Finalmente o fim de semana chegou!" },
  { id: 595, word: "INITIALLY", tip: "Inicialmente / A princípio", phonetic: "/ɪˈnɪʃ.əl.i/", example: "Initially it was hard, but it became easier.", examplePt: "Inicialmente foi difícil, mas ficou mais fácil." },
  { id: 596, word: "OBVIOUSLY", tip: "Obviamente / Evidentemente", phonetic: "/ˈɑːb.vi.əs.li/", example: "Obviously, regular practice leads to success.", examplePt: "Obviamente, a prática regular leva ao sucesso." },
  { id: 597, word: "APPARENTLY", tip: "Aparentemente / Pelo visto", phonetic: "/əˈper.ənt.li/", example: "Apparently, the weather is going to be sunny tomorrow.", examplePt: "Aparentemente, o tempo estará ensolarado amanhã." },
  { id: 598, word: "DEFINITELY", tip: "Com certeza / Definitivamente", phonetic: "/ˈdef.ən.ət.li/", example: "I will definitely join you for dinner.", examplePt: "Eu com certeza irei jantar com você." },
  { id: 599, word: "ABSOLUTELY", tip: "Absolutamente / Com certeza", phonetic: "/ˌæb.səˈluːt.li/", example: "You are absolutely right about this.", examplePt: "Você tem absoluta razão sobre isso." },
  { id: 600, word: "FORTUNATELY", tip: "Felizmente / Por sorte", phonetic: "/ˈfɔːr.tʃən.ət.li/", example: "Fortunately, we caught our connecting flight.", examplePt: "Felizmente, nós conseguimos pegar nosso voo de conexão." },
]
