import type { Challenge } from "../types"

export const WORDS_DIRECTIONS: Challenge[] = [
  { id: 601, word: "TURN LEFT", tip: "Vire à esquerda", phonetic: "/tɝːn left/", example: "Turn left at the next traffic light.", examplePt: "Vire à esquerda no próximo semáforo." },
  { id: 602, word: "TURN RIGHT", tip: "Vire à direita", phonetic: "/tɝːn raɪt/", example: "Turn right onto Fifth Avenue.", examplePt: "Vire à direita na Quinta Avenida." },
  { id: 603, word: "STRAIGHT AHEAD", tip: "Siga em frente / Direto", phonetic: "/ˌstreɪt əˈhed/", example: "Go straight ahead for two blocks.", examplePt: "Siga em frente por dois quarteirões." },
  { id: 604, word: "CORNER", tip: "Esquina / Canto", phonetic: "/ˈkɔːr.nɚ/", example: "The pharmacy is on the corner.", examplePt: "A farmácia fica na esquina." },
  { id: 605, word: "CROSSWALK", tip: "Faixa de pedestres", phonetic: "/ˈkrɑːs.wɑːk/", example: "Always cross the road on the crosswalk.", examplePt: "Sempre atravesse a rua na faixa de pedestres." },
  { id: 606, word: "TRAFFIC LIGHT", tip: "Semáforo / Sinal", phonetic: "/ˈtræf.ɪk ˌlaɪt/", example: "Wait for the traffic light to turn green.", examplePt: "Espere o semáforo ficar verde." },
  { id: 607, word: "ROUNDABOUT", tip: "Rotatória", phonetic: "/ˈraʊnd.ə.baʊt/", example: "Take the second exit at the roundabout.", examplePt: "Pegue a segunda saída na rotatória." },
  { id: 608, word: "HIGHWAY", tip: "Rodovia / Autoestrada", phonetic: "/ˈhaɪ.weɪ/", example: "Take the highway to reach the coast quickly.", examplePt: "Pegue a rodovia para chegar ao litoral rapidamente." },
  { id: 609, word: "BRIDGE", tip: "Ponte", phonetic: "/brɪdʒ/", example: "Drive across the Golden Gate bridge.", examplePt: "Atravesse a ponte Golden Gate de carro." },
  { id: 610, word: "TUNNEL", tip: "Túnel", phonetic: "/ˈtʌn.əl/", example: "Turn on your headlights inside the tunnel.", examplePt: "Acenda os faróis dentro do túnel." },
  { id: 611, word: "SIDEWALK", tip: "Calçada", phonetic: "/ˈsaɪd.wɑːk/", example: "Walk on the sidewalk for your safety.", examplePt: "Caminhe na calçada para sua segurança." },
  { id: 612, word: "PEDESTRIAN", tip: "Pedestre", phonetic: "/pəˈdes.tri.ən/", example: "Drivers must yield to pedestrians.", examplePt: "Motoristas devem dar preferência aos pedestres." },
  { id: 613, word: "AVENUE", tip: "Avenida", phonetic: "/ˈæv.ə.nuː/", example: "Walk along the tree-lined avenue.", examplePt: "Caminhe pela avenida arborizada." },
  { id: 614, word: "BOULEVARD", tip: "Bulevar / Alameda", phonetic: "/ˈbʊl.ə.vɑːrd/", example: "The central boulevard is full of cafes.", examplePt: "O bulevar central é repleto de cafés." },
  { id: 615, word: "CROSSROADS", tip: "Cruzamento", phonetic: "/ˈkrɑːs.roʊdz/", example: "Be cautious when approaching the crossroads.", examplePt: "Tenha cuidado ao se aproximar do cruzamento." },
  { id: 616, word: "NORTH", tip: "Norte", phonetic: "/nɔːrθ/", example: "Drive north toward Canada.", examplePt: "Dirija para o norte em direção ao Canadá." },
  { id: 617, word: "SOUTH", tip: "Sul", phonetic: "/saʊθ/", example: "Birds fly south for the winter.", examplePt: "Os pássaros voam para o sul no inverno." },
  { id: 618, word: "EAST", tip: "Leste / Oriente", phonetic: "/iːst/", example: "The sun rises in the east.", examplePt: "O sol nasce no leste." },
  { id: 619, word: "WEST", tip: "Oeste / Ocidente", phonetic: "/west/", example: "The sun sets in the west.", examplePt: "O sol se põe no oeste." },
  { id: 620, word: "MAP", tip: "Mapa", phonetic: "/mæp/", example: "Check your GPS map for the shortest route.", examplePt: "Verifique o mapa do GPS para a rota mais curta." },
  { id: 621, word: "NAVIGATION", tip: "Navegação / Orientação", phonetic: "/ˌnæv.əˈɡeɪ.ʃən/", example: "Set the destination in your navigation system.", examplePt: "Defina o destino no seu sistema de navegação." },
  { id: 622, word: "DISTANCE", tip: "Distância", phonetic: "/ˈdɪs.təns/", example: "The walking distance is only five minutes.", examplePt: "A distância a pé é de apenas cinco minutos." },
  { id: 623, word: "NEAR", tip: "Perto / Próximo", phonetic: "/nɪr/", example: "The train station is very near.", examplePt: "A estação de trem fica bem perto." },
  { id: 624, word: "FAR", tip: "Longe / Distante", phonetic: "/fɑːr/", example: "Is the international airport far from here?", examplePt: "O aeroporto internacional fica longe daqui?" },
  { id: 625, word: "BEHIND", tip: "Atrás de", phonetic: "/bɪˈhaɪnd/", example: "The parking lot is behind the building.", examplePt: "O estacionamento fica atrás do prédio." },
  { id: 626, word: "IN FRONT OF", tip: "Em frente a", phonetic: "/ɪn frʌnt əv/", example: "Meet me in front of the library.", examplePt: "Encontre-me em frente à biblioteca." },
  { id: 627, word: "NEXT TO", tip: "Ao lado de", phonetic: "/nekst tuː/", example: "The bakery is next to the bookstore.", examplePt: "A padaria fica ao lado da livraria." },
  { id: 628, word: "BETWEEN", tip: "Entre (duas coisas)", phonetic: "/bɪˈtwiːn/", example: "The cafe is between the bank and the post office.", examplePt: "O café fica entre o banco e o correio." },
  { id: 629, word: "OPPOSITE", tip: "Em frente / Do lado oposto", phonetic: "/ˈɑː.pə.zɪt/", example: "The hotel is opposite the main museum.", examplePt: "O hotel fica do lado oposto ao museu principal." },
  { id: 630, word: "GAS STATION", tip: "Posto de combustível", phonetic: "/ˈɡæs ˌsteɪ.ʃən/", example: "Stop at the gas station to fill up the tank.", examplePt: "Pare no posto de combustível para encher o tanque." },
  { id: 631, word: "PARKING LOT", tip: "Estacionamento", phonetic: "/ˈpɑːr.kɪŋ ˌlɑːt/", example: "Park your car in the designated parking lot.", examplePt: "Estacione seu carro no estacionamento indicado." },
  { id: 632, word: "SPEED LIMIT", tip: "Limite de velocidade", phonetic: "/ˈspiːd ˌlɪm.ɪt/", example: "Do not exceed the speed limit on this road.", examplePt: "Não ultrapasse o limite de velocidade nesta via." },
  { id: 633, word: "ONE WAY", tip: "Sentido único / Mão única", phonetic: "/ˌwʌn ˈweɪ/", example: "Watch out, this is a one way street!", examplePt: "Cuidado, esta rua é de mão única!" },
  { id: 634, word: "DEAD END", tip: "Rua sem saída", phonetic: "/ˌded ˈend/", example: "This small alley is a dead end.", examplePt: "Este pequeno beco é uma rua sem saída." },
  { id: 635, word: "BLOCK", tip: "Quarteirão / Bloco", phonetic: "/blɑːk/", example: "Walk three blocks and then turn left.", examplePt: "Caminhe três quarteirões e depois vire à esquerda." },
  { id: 636, word: "BUS STOP", tip: "Ponto de ônibus", phonetic: "/ˈbʌs ˌstɑːp/", example: "Wait at the bus stop for line 42.", examplePt: "Aguarde no ponto de ônibus pela linha 42." },
  { id: 637, word: "SUBWAY STATION", tip: "Estação de metrô", phonetic: "/ˈsʌb.weɪ ˌsteɪ.ʃən/", example: "Take the stairs down to the subway station.", examplePt: "Desça as escadas até a estação de metrô." },
  { id: 638, word: "TAXI STAND", tip: "Ponto de táxi", phonetic: "/ˈtæk.si ˌstænd/", example: "You will find available cars at the taxi stand.", examplePt: "Você encontrará carros disponíveis no ponto de táxi." },
  { id: 639, word: "EXIT", tip: "Saída", phonetic: "/ˈeɡ.zɪt/", example: "Take exit 14 to enter downtown.", examplePt: "Pegue a saída 14 para entrar no centro." },
  { id: 640, word: "ENTRANCE", tip: "Entrada", phonetic: "/ˈen.trəns/", example: "The main entrance is wheelchair accessible.", examplePt: "A entrada principal tem acesso para cadeirantes." },
  { id: 641, word: "U-TURN", tip: "Retorno / Conversão em U", phonetic: "/ˈjuː.tɝːn/", example: "Make a legal U-turn at the intersection.", examplePt: "Faça um retorno permitido no cruzamento." },
  { id: 642, word: "OVERPASS", tip: "Viaduto / Passarela", phonetic: "/ˈoʊ.vɚ.pæs/", example: "Drive over the highway overpass.", examplePt: "Passe por cima do viaduto da rodovia." },
  { id: 643, word: "TRAFFIC JAM", tip: "Congestionamento / Trânsito parado", phonetic: "/ˈtræf.ɪk ˌdʒæm/", example: "We were stuck in a bad traffic jam for an hour.", examplePt: "Ficamos presos em um grande engarrafamento por uma hora." },
  { id: 644, word: "DETOUR", tip: "Desvio na estrada", phonetic: "/ˈdiː.tʊr/", example: "Follow the detour signs around road construction.", examplePt: "Siga as placas de desvio contornando as obras na pista." },
  { id: 645, word: "ACCIDENT", tip: "Acidente", phonetic: "/ˈæk.sə.dənt/", example: "Drive defensively to avoid any accident.", examplePt: "Dirija defensivamente para evitar qualquer acidente." },
  { id: 646, word: "SEATBELT", tip: "Cinto de segurança", phonetic: "/ˈsiːt.belt/", example: "Fasten your seatbelt before driving.", examplePt: "Afivele seu cinto de segurança antes de dirigir." },
  { id: 647, word: "DRIVER", tip: "Motorista / Condutor", phonetic: "/ˈdraɪ.vɚ/", example: "The bus driver was very helpful.", examplePt: "O motorista de ônibus foi muito prestativo." },
  { id: 648, word: "PASSENGER", tip: "Passageiro", phonetic: "/ˈpæs.ən.dʒɚ/", example: "All passengers must remain seated.", examplePt: "Todos os passageiros devem permanecer sentados." },
  { id: 649, word: "LOCATION", tip: "Localização / Ponto", phonetic: "/loʊˈkeɪ.ʃən/", example: "Share your live location with family.", examplePt: "Compartilhe sua localização em tempo real com a família." },
  { id: 650, word: "DESTINATION REACHED", tip: "Destino alcançado / Chegou ao local", phonetic: "/ˌdes.təˈneɪ.ʃən riːtʃt/", example: "Your GPS announces: destination reached!", examplePt: "Seu GPS anuncia: destino alcançado!" },
]
