export type Challenge = {
  id: number
  word: string
  tip: string
}

export const WORDS_VERBS: Challenge[] = [
  { id: 1, word: "BE", tip: "Ser / Estar" },
  { id: 2, word: "HAVE", tip: "Ter" },
  { id: 3, word: "DO", tip: "Fazer" },
  { id: 4, word: "SAY", tip: "Dizer" },
  { id: 5, word: "GO", tip: "Ir" },
  { id: 6, word: "GET", tip: "Obter / Conseguir" },
  { id: 7, word: "MAKE", tip: "Fazer / Criar" },
  { id: 8, word: "KNOW", tip: "Saber / Conhecer" },
  { id: 9, word: "THINK", tip: "Pensar" },
  { id: 10, word: "TAKE", tip: "Pegar / Levar" },
  { id: 11, word: "SEE", tip: "Ver" },
  { id: 12, word: "COME", tip: "Vir" },
  { id: 13, word: "WANT", tip: "Querer" },
  { id: 14, word: "LOOK", tip: "Olhar / Parecer" },
  { id: 15, word: "USE", tip: "Usar" },
  { id: 16, word: "FIND", tip: "Encontrar" },
  { id: 17, word: "GIVE", tip: "Dar" },
  { id: 18, word: "TELL", tip: "Contar / Dizer" },
  { id: 19, word: "WORK", tip: "Trabalhar" },
  { id: 20, word: "CALL", tip: "Ligar / Chamar" },
  { id: 21, word: "TRY", tip: "Tentar" },
  { id: 22, word: "ASK", tip: "Perguntar / Pedir" },
  { id: 23, word: "NEED", tip: "Precisar" },
  { id: 24, word: "FEEL", tip: "Sentir" },
  { id: 25, word: "BECOME", tip: "Tornar-se" },
  { id: 26, word: "LEAVE", tip: "Sair / Deixar" },
  { id: 27, word: "PUT", tip: "Colocar" },
  { id: 28, word: "MEAN", tip: "Significar" },
  { id: 29, word: "KEEP", tip: "Manter / Guardar" },
  { id: 30, word: "LET", tip: "Deixar / Permitir" },
  { id: 31, word: "BEGIN", tip: "Começar" },
  { id: 32, word: "SEEM", tip: "Parecer" },
  { id: 33, word: "HELP", tip: "Ajudar" },
  { id: 34, word: "SHOW", tip: "Mostrar" },
  { id: 35, word: "HEAR", tip: "Ouvir" },
  { id: 36, word: "PLAY", tip: "Jogar / Tocar (instrumento)" },
  { id: 37, word: "RUN", tip: "Correr" },
  { id: 38, word: "MOVE", tip: "Mover / Mudar-se" },
  { id: 39, word: "LIVE", tip: "Viver / Morar" },
  { id: 40, word: "BELIEVE", tip: "Acreditar" },
  { id: 41, word: "BRING", tip: "Trazer" },
  { id: 42, word: "HAPPEN", tip: "Acontecer" },
  { id: 43, word: "WRITE", tip: "Escrever" },
  { id: 44, word: "SIT", tip: "Sentar" },
  { id: 45, word: "STAND", tip: "Ficar de pé" },
  { id: 46, word: "LOSE", tip: "Perder" },
  { id: 47, word: "PAY", tip: "Pagar" },
  { id: 48, word: "MEET", tip: "Conhecer / Encontrar" },
  { id: 49, word: "INCLUDE", tip: "Incluir" },
  { id: 50, word: "UNDERSTAND", tip: "Entender / Compreender" },
]
