import type { Challenge } from "../types"

export const WORDS_VERBS: Challenge[] = [
  { id: 51, word: "BE", tip: "Ser / Estar", phonetic: "/biː/", example: "Be yourself no matter what.", examplePt: "Seja você mesmo, não importa o que aconteça." },
  { id: 52, word: "HAVE", tip: "Ter", phonetic: "/hæv/", example: "I have two brothers.", examplePt: "Eu tenho dois irmãos." },
  { id: 53, word: "DO", tip: "Fazer", phonetic: "/duː/", example: "What do you want to do today?", examplePt: "O que você quer fazer hoje?" },
  { id: 54, word: "SAY", tip: "Dizer", phonetic: "/seɪ/", example: "What did you say to him?", examplePt: "O que você disse para ele?" },
  { id: 55, word: "GO", tip: "Ir", phonetic: "/ɡoʊ/", example: "Let's go to the park.", examplePt: "Vamos ao parque." },
  { id: 56, word: "GET", tip: "Obter / Conseguir", phonetic: "/ɡet/", example: "Did you get my message?", examplePt: "Você recebeu minha mensagem?" },
  { id: 57, word: "MAKE", tip: "Fazer / Criar", phonetic: "/meɪk/", example: "She can make delicious cakes.", examplePt: "Ela sabe fazer bolos deliciosos." },
  { id: 58, word: "KNOW", tip: "Saber / Conhecer", phonetic: "/noʊ/", example: "I know the answer to this question.", examplePt: "Eu sei a resposta para esta pergunta." },
  { id: 59, word: "THINK", tip: "Pensar", phonetic: "/θɪŋk/", example: "I think it is going to rain.", examplePt: "Eu acho que vai chover." },
  { id: 60, word: "TAKE", tip: "Pegar / Levar", phonetic: "/teɪk/", example: "Take an umbrella with you.", examplePt: "Leve um guarda-chuva com você." },
  { id: 61, word: "SEE", tip: "Ver", phonetic: "/siː/", example: "I can see the ocean from here.", examplePt: "Consigo ver o oceano daqui." },
  { id: 62, word: "COME", tip: "Vir", phonetic: "/kʌm/", example: "Come here for a moment.", examplePt: "Venha aqui por um instante." },
  { id: 63, word: "WANT", tip: "Querer", phonetic: "/wɑːnt/", example: "I want to learn English quickly.", examplePt: "Quero aprender inglês rapidamente." },
  { id: 64, word: "LOOK", tip: "Olhar / Parecer", phonetic: "/lʊk/", example: "Look at the stars tonight.", examplePt: "Olhe para as estrelas hoje à noite." },
  { id: 65, word: "USE", tip: "Usar", phonetic: "/juːz/", example: "Can I use your dictionary?", examplePt: "Posso usar o seu dicionário?" },
  { id: 66, word: "FIND", tip: "Encontrar", phonetic: "/faɪnd/", example: "I hope you find your keys.", examplePt: "Espero que você encontre suas chaves." },
  { id: 67, word: "GIVE", tip: "Dar", phonetic: "/ɡɪv/", example: "Please give me some advice.", examplePt: "Por favor, me dê um conselho." },
  { id: 68, word: "TELL", tip: "Contar / Dizer", phonetic: "/tel/", example: "Tell me a story.", examplePt: "Conte-me uma história." },
  { id: 69, word: "WORK", tip: "Trabalhar", phonetic: "/wɜːrk/", example: "I work from Monday to Friday.", examplePt: "Eu trabalho de segunda a sexta." },
  { id: 70, word: "CALL", tip: "Ligar / Chamar", phonetic: "/kɔːl/", example: "I will call you later tonight.", examplePt: "Vou te ligar mais tarde hoje à noite." },
  { id: 71, word: "TRY", tip: "Tentar", phonetic: "/traɪ/", example: "Always try your best.", examplePt: "Sempre tente o seu melhor." },
  { id: 72, word: "ASK", tip: "Perguntar / Pedir", phonetic: "/æsk/", example: "Feel free to ask questions.", examplePt: "Sinta-se livre para fazer perguntas." },
  { id: 73, word: "NEED", tip: "Precisar", phonetic: "/niːd/", example: "We need more time to study.", examplePt: "Precisamos de mais tempo para estudar." },
  { id: 74, word: "FEEL", tip: "Sentir", phonetic: "/fiːl/", example: "I feel great today.", examplePt: "Estou me sentindo ótimo hoje." },
  { id: 75, word: "BECOME", tip: "Tornar-se", phonetic: "/bɪˈkʌm/", example: "She wants to become a doctor.", examplePt: "Ela quer se tornar uma médica." },
  { id: 76, word: "LEAVE", tip: "Sair / Deixar", phonetic: "/liːv/", example: "We leave the house at 7 AM.", examplePt: "Nós saímos de casa às 7h da manhã." },
  { id: 77, word: "PUT", tip: "Colocar", phonetic: "/pʊt/", example: "Put your phone on the desk.", examplePt: "Coloque seu telefone na mesa." },
  { id: 78, word: "MEAN", tip: "Significar", phonetic: "/miːn/", example: "What does this word mean?", examplePt: "O que esta palavra significa?" },
  { id: 79, word: "KEEP", tip: "Manter / Guardar", phonetic: "/kiːp/", example: "Keep practicing every single day.", examplePt: "Continue praticando todos os dias." },
  { id: 80, word: "LET", tip: "Deixar / Permitir", phonetic: "/let/", example: "Let me know when you arrive.", examplePt: "Avise-me quando você chegar." },
  { id: 81, word: "BEGIN", tip: "Começar", phonetic: "/bɪˈɡɪn/", example: "Class will begin shortly.", examplePt: "A aula vai começar em breve." },
  { id: 82, word: "SEEM", tip: "Parecer", phonetic: "/siːm/", example: "Everything seems fine.", examplePt: "Tudo parece bem." },
  { id: 83, word: "HELP", tip: "Ajudar", phonetic: "/help/", example: "Can you help me with this?", examplePt: "Você pode me ajudar com isso?" },
  { id: 84, word: "SHOW", tip: "Mostrar", phonetic: "/ʃoʊ/", example: "Let me show you how it works.", examplePt: "Deixe-me mostrar como funciona." },
  { id: 85, word: "HEAR", tip: "Ouvir", phonetic: "/hɪr/", example: "Did you hear that noise?", examplePt: "Você ouviu aquele barulho?" },
  { id: 86, word: "PLAY", tip: "Jogar / Tocar (instrumento)", phonetic: "/pleɪ/", example: "I love to play the guitar.", examplePt: "Eu amo tocar violão." },
  { id: 87, word: "RUN", tip: "Correr", phonetic: "/rʌn/", example: "He runs five miles every morning.", examplePt: "Ele corre oito quilômetros toda manhã." },
  { id: 88, word: "MOVE", tip: "Mover / Mudar-se", phonetic: "/muːv/", example: "They decided to move to London.", examplePt: "Eles decidiram se mudar para Londres." },
  { id: 89, word: "LIVE", tip: "Viver / Morar", phonetic: "/lɪv/", example: "Where do you live?", examplePt: "Onde você mora?" },
  { id: 90, word: "BELIEVE", tip: "Acreditar", phonetic: "/bɪˈliːv/", example: "Believe in yourself.", examplePt: "Acredite em si mesmo." },
  { id: 91, word: "BRING", tip: "Trazer", phonetic: "/brɪŋ/", example: "Please bring your notebook.", examplePt: "Por favor, traga seu caderno." },
  { id: 92, word: "HAPPEN", tip: "Acontecer", phonetic: "/ˈhæp.ən/", example: "Accidents can happen anytime.", examplePt: "Acidentes podem acontecer a qualquer momento." },
  { id: 93, word: "WRITE", tip: "Escrever", phonetic: "/raɪt/", example: "Write down your daily goals.", examplePt: "Escreva suas metas diárias." },
  { id: 94, word: "SIT", tip: "Sentar", phonetic: "/sɪt/", example: "Please sit down and relax.", examplePt: "Por favor, sente-se e relaxe." },
  { id: 95, word: "STAND", tip: "Ficar de pé", phonetic: "/stænd/", example: "Please stand behind the yellow line.", examplePt: "Por favor, fique de pé atrás da linha amarela." },
  { id: 96, word: "LOSE", tip: "Perder", phonetic: "/luːz/", example: "Do not lose hope.", examplePt: "Não perca a esperança." },
  { id: 97, word: "PAY", tip: "Pagar", phonetic: "/peɪ/", example: "You can pay by credit card.", examplePt: "Você pode pagar com cartão de crédito." },
  { id: 98, word: "MEET", tip: "Conhecer / Encontrar", phonetic: "/miːt/", example: "Nice to meet you!", examplePt: "Prazer em conhecer você!" },
  { id: 99, word: "INCLUDE", tip: "Incluir", phonetic: "/ɪnˈkluːd/", example: "Does the price include breakfast?", examplePt: "O preço inclui café da manhã?" },
  { id: 100, word: "UNDERSTAND", tip: "Entender / Compreender", phonetic: "/ˌʌn.dɚˈstænd/", example: "I understand English very well.", examplePt: "Eu entendo inglês muito bem." },
]
