import type { Challenge } from "../types"

export const WORDS_HEALTH: Challenge[] = [
  { id: 401, word: "DOCTOR", tip: "Médico / Doutor", phonetic: "/ˈdɑːk.tɚ/", example: "See a doctor if fever continues.", examplePt: "Consulte um médico se a febre continuar." },
  { id: 402, word: "NURSE", tip: "Enfermeiro(a)", phonetic: "/nɝːs/", example: "The nurse checked my blood pressure.", examplePt: "A enfermeira verificou minha pressão arterial." },
  { id: 403, word: "HOSPITAL", tip: "Hospital", phonetic: "/ˈhɑː.spɪ.t̬əl/", example: "The emergency hospital is down the street.", examplePt: "O hospital de emergência fica no fim da rua." },
  { id: 404, word: "CLINIC", tip: "Clínica médica", phonetic: "/ˈklɪn.ɪk/", example: "I have an appointment at the dental clinic.", examplePt: "Tenho uma consulta na clínica odontológica." },
  { id: 405, word: "PHARMACY", tip: "Farmácia", phonetic: "/ˈfɑːr.mə.si/", example: "Buy your medicine at the pharmacy.", examplePt: "Compre seu remédio na farmácia." },
  { id: 406, word: "MEDICINE", tip: "Remédio / Medicamento", phonetic: "/ˈmed.ə.sɪn/", example: "Take this medicine twice a day.", examplePt: "Tome este medicamento duas vezes ao dia." },
  { id: 407, word: "PAIN", tip: "Dor", phonetic: "/peɪn/", example: "Where do you feel the pain?", examplePt: "Onde você sente a dor?" },
  { id: 408, word: "HEADACHE", tip: "Dor de cabeça", phonetic: "/ˈhed.eɪk/", example: "I have a mild headache.", examplePt: "Estou com uma leve dor de cabeça." },
  { id: 409, word: "FEVER", tip: "Febre", phonetic: "/ˈfiː.vɚ/", example: "Drink water to lower your high fever.", examplePt: "Beba água para baixar sua febre alta." },
  { id: 410, word: "COUGH", tip: "Tosse / Tossir", phonetic: "/kɑːf/", example: "Cover your mouth when you cough.", examplePt: "Cubra a boca quando você tossir." },
  { id: 411, word: "COLD", tip: "Resfriado", phonetic: "/koʊld/", example: "I caught a bad cold this winter.", examplePt: "Peguei um resfriado forte neste inverno." },
  { id: 412, word: "FLU", tip: "Gripe", phonetic: "/fluː/", example: "Get vaccinated against the seasonal flu.", examplePt: "Vacine-se contra a gripe sazonal." },
  { id: 413, word: "STOMACHACHE", tip: "Dor de estômago / Barriga", phonetic: "/ˈstʌm.ək.eɪk/", example: "He has a stomachache after eating too much.", examplePt: "Ele está com dor de estômago depois de comer demais." },
  { id: 414, word: "TOOTHACHE", tip: "Dor de dente", phonetic: "/ˈtuːθ.eɪk/", example: "Visit the dentist to treat your toothache.", examplePt: "Visite o dentista para tratar sua dor de dente." },
  { id: 415, word: "DENTIST", tip: "Dentista", phonetic: "/ˈden.t̬ɪst/", example: "I go to the dentist every six months.", examplePt: "Eu vou ao dentista a cada seis meses." },
  { id: 416, word: "APPOINTMENT", tip: "Consulta médica / Agendamento", phonetic: "/əˈpɔɪnt.mənt/", example: "My doctor appointment is at 3 PM.", examplePt: "Minha consulta médica é às 15h." },
  { id: 417, word: "PRESCRIPTION", tip: "Receita médica", phonetic: "/prɪˈskrɪp.ʃən/", example: "You need a prescription for antibiotics.", examplePt: "Você precisa de uma receita para antibióticos." },
  { id: 418, word: "VITAMIN", tip: "Vitamina", phonetic: "/ˈvaɪ.t̬ə.mɪn/", example: "Vitamin C boosts your immune system.", examplePt: "Vitamina C fortalece o seu sistema imunológico." },
  { id: 419, word: "EXERCISE", tip: "Exercício físico / Praticar", phonetic: "/ˈek.sɚ.saɪz/", example: "Daily exercise keeps your heart healthy.", examplePt: "Exercício diário mantém o coração saudável." },
  { id: 420, word: "DIET", tip: "Dieta / Alimentação", phonetic: "/ˈdaɪ.ət/", example: "A balanced diet contains vegetables and fruits.", examplePt: "Uma dieta equilibrada contém legumes e frutas." },
  { id: 421, word: "REST", tip: "Descanso / Descansar", phonetic: "/rest/", example: "Your body needs plenty of rest.", examplePt: "Seu corpo precisa de bastante descanso." },
  { id: 422, word: "SLEEP", tip: "Sono / Dormir", phonetic: "/sliːp/", example: "Get eight hours of sleep every night.", examplePt: "Durma oito horas de sono toda noite." },
  { id: 423, word: "HEALTHY", tip: "Saudável", phonetic: "/ˈhel.θi/", example: "Eating fresh food keeps you healthy.", examplePt: "Comer alimentos frescos mantém você saudável." },
  { id: 424, word: "SICK", tip: "Doente", phonetic: "/sɪk/", example: "Stay home if you feel sick.", examplePt: "Fique em casa se você se sentir doente." },
  { id: 425, word: "HEART", tip: "Coração", phonetic: "/hɑːrt/", example: "Cardio workouts strengthen your heart.", examplePt: "Treinos aeróbicos fortalecem seu coração." },
  { id: 426, word: "BRAIN", tip: "Cérebro", phonetic: "/breɪn/", example: "Learning new words exercises your brain.", examplePt: "Aprender palavras novas exercita seu cérebro." },
  { id: 427, word: "BLOOD", tip: "Sangue", phonetic: "/blʌd/", example: "Blood carries oxygen throughout the body.", examplePt: "O sangue transporta oxigênio por todo o corpo." },
  { id: 428, word: "BONE", tip: "Osso", phonetic: "/boʊn/", example: "Calcium is essential for strong bones.", examplePt: "Cálcio é essencial para ossos fortes." },
  { id: 429, word: "MUSCLE", tip: "Músculo", phonetic: "/ˈmʌs.əl/", example: "Strength training builds muscle mass.", examplePt: "Treino de força desenvolve massa muscular." },
  { id: 430, word: "SKIN", tip: "Pele", phonetic: "/skɪn/", example: "Protect your skin from strong sunlight.", examplePt: "Proteja sua pele da luz solar forte." },
  { id: 431, word: "BREATHE", tip: "Respirar", phonetic: "/briːð/", example: "Breathe deeply through your nose.", examplePt: "Respire fundo pelo nariz." },
  { id: 432, word: "INJURY", tip: "Lesão / Ferimento", phonetic: "/ˈɪn.dʒər.i/", example: "He recovered quickly from a minor sports injury.", examplePt: "Ele se recuperou rápido de uma pequena lesão esportiva." },
  { id: 433, word: "BANDAGE", tip: "Curativo / Bandagem", phonetic: "/ˈbæn.dɪdʒ/", example: "Put a clean bandage on the cut.", examplePt: "Coloque um curativo limpo no corte." },
  { id: 434, word: "SURGERY", tip: "Cirurgia", phonetic: "/ˈsɝː.dʒər.i/", example: "The knee surgery was completely successful.", examplePt: "A cirurgia no joelho foi um sucesso total." },
  { id: 435, word: "EMERGENCY", tip: "Emergência", phonetic: "/ɪˈmɝː.dʒən.si/", example: "Call 911 in case of medical emergency.", examplePt: "Ligue para o serviço de emergência médica." },
  { id: 436, word: "AMBULANCE", tip: "Ambulância", phonetic: "/ˈæm.bjə.ləns/", example: "The ambulance arrived within five minutes.", examplePt: "A ambulância chegou em cinco minutos." },
  { id: 437, word: "THERAPY", tip: "Terapia / Tratamento", phonetic: "/ˈθer.ə.pi/", example: "Physical therapy helped him walk again.", examplePt: "A fisioterapia o ajudou a caminhar novamente." },
  { id: 438, word: "ALLERGY", tip: "Alergia", phonetic: "/ˈæl.ɚ.dʒi/", example: "Do you have any food allergy?", examplePt: "Você tem alguma alergia alimentar?" },
  { id: 439, word: "VACCINE", tip: "Vacina", phonetic: "/vækˈsiːn/", example: "Vaccines protect communities against diseases.", examplePt: "Vacinas protegem comunidades contra doenças." },
  { id: 440, word: "WELLNESS", tip: "Bem-estar", phonetic: "/ˈwel.nəs/", example: "Focus on mental and physical wellness.", examplePt: "Foque no bem-estar físico e mental." },
  { id: 441, word: "SORE THROAT", tip: "Dor de garganta", phonetic: "/ˌsɔːr ˈθroʊt/", example: "Warm tea with honey helps a sore throat.", examplePt: "Chá quente com mel ajuda na dor de garganta." },
  { id: 442, word: "STOMACH", tip: "Estômago", phonetic: "/ˈstʌm.ək/", example: "Do not exercise on a full stomach.", examplePt: "Não faça exercícios de estômago cheio." },
  { id: 443, word: "FEELING BETTER", tip: "Sentindo-se melhor", phonetic: "/ˈfiː.lɪŋ ˈbet̬.ɚ/", example: "I am finally feeling better today.", examplePt: "Estou finalmente me sentindo melhor hoje." },
  { id: 444, word: "CHECK-UP", tip: "Exame de rotina / Check-up", phonetic: "/ˈtʃek.ʌp/", example: "Schedule an annual medical check-up.", examplePt: "Agende um check-up médico anual." },
  { id: 445, word: "FIRST AID", tip: "Primeiros socorros", phonetic: "/ˌfɝːst ˈeɪd/", example: "Keep a first aid kit in your car.", examplePt: "Mantenha um kit de primeiros socorros no carro." },
  { id: 446, word: "HYDRATION", tip: "Hidratação", phonetic: "/haɪˈdreɪ.ʃən/", example: "Hydration is essential during summer.", examplePt: "Hidratação é essencial durante o verão." },
  { id: 447, word: "ENERGY", tip: "Energia / Disposição", phonetic: "/ˈen.ɚ.dʒi/", example: "Good nutrition gives you steady energy.", examplePt: "Boa nutrição fornece energia constante." },
  { id: 448, word: "RELAXATION", tip: "Relaxamento", phonetic: "/ˌriː.lækˈseɪ.ʃən/", example: "Meditation promotes deep relaxation.", examplePt: "Meditação promove relaxamento profundo." },
  { id: 449, word: "RECOVERY", tip: "Recuperação", phonetic: "/rɪˈkʌv.ɚ.i/", example: "We wish you a speedy recovery.", examplePt: "Desejamos a você uma rápida recuperação." },
  { id: 450, word: "STRENGTH", tip: "Força / Vigor", phonetic: "/streŋθ/", example: "Daily workouts build physical strength.", examplePt: "Treinos diários desenvolvem força física." },
]
