import type { Challenge } from "../types"

export const WORDS_SHOPPING: Challenge[] = [
  { id: 351, word: "STORE", tip: "Loja", phonetic: "/stɔːr/", example: "The grocery store opens at 8 AM.", examplePt: "A mercearia abre às 8h da manhã." },
  { id: 352, word: "MALL", tip: "Shopping center", phonetic: "/mɑːl/", example: "We spent the afternoon at the mall.", examplePt: "Passamos a tarde no shopping center." },
  { id: 353, word: "PRICE", tip: "Preço", phonetic: "/praɪs/", example: "What is the price of this shirt?", examplePt: "Qual é o preço desta camisa?" },
  { id: 354, word: "DISCOUNT", tip: "Desconto", phonetic: "/ˈdɪs.kaʊnt/", example: "They offer a 20% student discount.", examplePt: "Eles oferecem 20% de desconto para estudantes." },
  { id: 355, word: "SALE", tip: "Promoção / Liquidação", phonetic: "/seɪl/", example: "Winter clothes are on sale now.", examplePt: "As roupas de inverno estão em promoção agora." },
  { id: 356, word: "CASH", tip: "Dinheiro em espécie", phonetic: "/kæʃ/", example: "Do you prefer to pay in cash or card?", examplePt: "Você prefere pagar em dinheiro ou cartão?" },
  { id: 357, word: "CREDIT CARD", tip: "Cartão de crédito", phonetic: "/ˈkred.ɪt ˌkɑːrd/", example: "Can I pay with a credit card?", examplePt: "Posso pagar com cartão de crédito?" },
  { id: 358, word: "RECEIPT", tip: "Recibo / Nota fiscal", phonetic: "/rɪˈsiːt/", example: "Keep your receipt for returns.", examplePt: "Guarde seu recibo para trocas." },
  { id: 359, word: "REFUND", tip: "Reembolso", phonetic: "/ˈriː.fʌnd/", example: "I asked for a full refund.", examplePt: "Pedi um reembolso total." },
  { id: 360, word: "EXPENSIVE", tip: "Caro", phonetic: "/ɪkˈspen.sɪv/", example: "That designer jacket is too expensive.", examplePt: "Aquela jaqueta de grife é cara demais." },
  { id: 361, word: "CHEAP", tip: "Barato", phonetic: "/tʃiːp/", example: "These sunglasses were very cheap.", examplePt: "Estes óculos de sol foram muito baratos." },
  { id: 362, word: "SIZE", tip: "Tamanho", phonetic: "/saɪz/", example: "What size do you wear in shirts?", examplePt: "Qual tamanho você veste de camisa?" },
  { id: 363, word: "FITTING ROOM", tip: "Provador de roupas", phonetic: "/ˈfɪt̬.ɪŋ ˌruːm/", example: "Where is the fitting room located?", examplePt: "Onde fica o provador de roupas?" },
  { id: 364, word: "SHIRT", tip: "Camisa", phonetic: "/ʃɝːt/", example: "He wore a crisp white shirt.", examplePt: "Ele vestiu uma camisa branca impecável." },
  { id: 365, word: "T-SHIRT", tip: "Camiseta", phonetic: "/ˈtiː.ʃɝːt/", example: "I bought a comfortable cotton t-shirt.", examplePt: "Comprei uma camiseta de algodão confortável." },
  { id: 366, word: "PANTS", tip: "Calças", phonetic: "/pænts/", example: "These black pants fit perfectly.", examplePt: "Estas calças pretas vestem perfeitamente." },
  { id: 367, word: "JEANS", tip: "Calça jeans", phonetic: "/dʒiːnz/", example: "Blue jeans are timeless and stylish.", examplePt: "Calça jeans azul é atemporal e estilosa." },
  { id: 368, word: "JACKET", tip: "Jaqueta / Casaco", phonetic: "/ˈdʒæk.ɪt/", example: "Put on your leather jacket.", examplePt: "Coloque sua jaqueta de couro." },
  { id: 369, word: "COAT", tip: "Sobretudo / Casaco pesado", phonetic: "/koʊt/", example: "Wear a heavy coat in the snow.", examplePt: "Use um casaco pesado na neve." },
  { id: 370, word: "DRESS", tip: "Vestido", phonetic: "/dres/", example: "She wore an elegant evening dress.", examplePt: "Ela usou um vestido de noite elegante." },
  { id: 371, word: "SKIRT", tip: "Saia", phonetic: "/skɝːt/", example: "The pleated skirt looks nice.", examplePt: "A saia plissada fica muito bonita." },
  { id: 372, word: "SOCKS", tip: "Meias", phonetic: "/sɑːks/", example: "Warm wool socks for cold feet.", examplePt: "Meias de lã quentes para pés frios." },
  { id: 373, word: "BOOTS", tip: "Botas", phonetic: "/buːts/", example: "Waterproof boots for hiking in the rain.", examplePt: "Botas impermeáveis para caminhar na chuva." },
  { id: 374, word: "SNEAKERS", tip: "Tênis", phonetic: "/ˈsniː.kɚz/", example: "Running sneakers with good cushioning.", examplePt: "Tênis de corrida com bom amortecimento." },
  { id: 375, word: "HAT", tip: "Chapéu", phonetic: "/hæt/", example: "Wear a wide hat to block the sun.", examplePt: "Use um chapéu de abas largas para bloquear o sol." },
  { id: 376, word: "CAP", tip: "Boné", phonetic: "/kæp/", example: "He wears a baseball cap every day.", examplePt: "Ele usa um boné de beisebol todos os dias." },
  { id: 377, word: "BELT", tip: "Cinto", phonetic: "/belt/", example: "A brown leather belt matches those shoes.", examplePt: "Um cinto de couro marrom combina com aqueles sapatos." },
  { id: 378, word: "WATCH", tip: "Relógio de pulso", phonetic: "/wɑːtʃ/", example: "He checked his gold watch.", examplePt: "Ele olhou para o seu relógio de ouro." },
  { id: 379, word: "SUNGLASSES", tip: "Óculos de sol", phonetic: "/ˈsʌnˌɡlæs.ɪz/", example: "Do not forget your sunglasses at the beach.", examplePt: "Não se esqueça dos seus óculos de sol na praia." },
  { id: 380, word: "WALLET", tip: "Carteira", phonetic: "/ˈwɑː.lɪt/", example: "He kept his cash inside the wallet.", examplePt: "Ele guardava o dinheiro dentro da carteira." },
  { id: 381, word: "PURSE", tip: "Bolsa feminina", phonetic: "/pɝːs/", example: "She searched for her keys in her purse.", examplePt: "Ela procurou as chaves dentro da sua bolsa." },
  { id: 382, word: "JEWELRY", tip: "Joias / Bijuterias", phonetic: "/ˈdʒuː.əl.ri/", example: "Silver jewelry is very popular.", examplePt: "Joias de prata são muito populares." },
  { id: 383, word: "RING", tip: "Anel / Aliança", phonetic: "/rɪŋ/", example: "A diamond engagement ring.", examplePt: "Um anel de noivado de diamante." },
  { id: 384, word: "NECKLACE", tip: "Colar", phonetic: "/ˈnek.ləs/", example: "She wore a delicate pearl necklace.", examplePt: "Ela usava um delicado colar de pérolas." },
  { id: 385, word: "BUY", tip: "Comprar", phonetic: "/baɪ/", example: "I want to buy a new laptop.", examplePt: "Quero comprar um laptop novo." },
  { id: 386, word: "SELL", tip: "Vender", phonetic: "/sel/", example: "They sell handcrafted souvenirs.", examplePt: "Eles vendem lembrancinhas feitas à mão." },
  { id: 387, word: "PAY", tip: "Pagar", phonetic: "/peɪ/", example: "Let me pay for our coffees.", examplePt: "Deixe-me pagar nossos cafés." },
  { id: 388, word: "SPEND", tip: "Gastar (dinheiro / tempo)", phonetic: "/spend/", example: "Try not to spend too much money.", examplePt: "Tente não gastar muito dinheiro." },
  { id: 389, word: "SAVE", tip: "Economizar / Salvar", phonetic: "/seɪv/", example: "Save money each month for travel.", examplePt: "Economize dinheiro todo mês para viajar." },
  { id: 390, word: "CUSTOMER", tip: "Cliente / Freguês", phonetic: "/ˈkʌs.tə.mɚ/", example: "The shop assistant helped the customer.", examplePt: "A atendente ajudou o cliente." },
  { id: 391, word: "CASHIER", tip: "Caixa (funcionário)", phonetic: "/kæʃˈɪr/", example: "Pay the friendly cashier at the counter.", examplePt: "Pague ao simpático caixa no balcão." },
  { id: 392, word: "CART", tip: "Carrinho de compras", phonetic: "/kɑːrt/", example: "Fill your shopping cart with fresh food.", examplePt: "Encha seu carrinho de compras com alimentos frescos." },
  { id: 393, word: "BASKET", tip: "Cesta de compras", phonetic: "/ˈbæs.kət/", example: "Grab a small basket near the entrance.", examplePt: "Pegue uma cestinha perto da entrada." },
  { id: 394, word: "AISLE", tip: "Corredor (de supermercado/loja)", phonetic: "/aɪl/", example: "You can find pasta in aisle four.", examplePt: "Você encontra massa no corredor quatro." },
  { id: 395, word: "BARGAIN", tip: "Pechincha / Bom negócio", phonetic: "/ˈbɑːr.ɡɪn/", example: "This warm sweater was a real bargain.", examplePt: "Este suéter quentinho foi uma verdadeira pechincha." },
  { id: 396, word: "BRAND", tip: "Marca", phonetic: "/brænd/", example: "What is your favorite clothing brand?", examplePt: "Qual é a sua marca de roupas favorita?" },
  { id: 397, word: "QUALITY", tip: "Qualidade", phonetic: "/ˈkwɑː.lə.t̬i/", example: "High quality materials last longer.", examplePt: "Materiais de alta qualidade duram mais tempo." },
  { id: 398, word: "COTTON", tip: "Algodão", phonetic: "/ˈkɑː.tən/", example: "100% pure organic cotton.", examplePt: "100% puro algodão orgânico." },
  { id: 399, word: "LEATHER", tip: "Couro", phonetic: "/ˈleð.ɚ/", example: "Genuine leather shoes.", examplePt: "Sapatos de couro legítimo." },
  { id: 400, word: "WOOL", tip: "Lã", phonetic: "/wʊl/", example: "This warm wool scarf is handmade.", examplePt: "Este cachecol de lã quentinho é feito à mão." },
]
