export type Challenge = {
  id: number
  word: string
  tip: string
}

export const WORDS_TRAVEL: Challenge[] = [
  { id: 1, word: "AIRPORT", tip: "Aeroporto" },
  { id: 2, word: "PLANE", tip: "Avião" },
  { id: 3, word: "FLIGHT", tip: "Voo" },
  { id: 4, word: "BOARDING PASS", tip: "Cartão de embarque" },
  { id: 5, word: "LUGGAGE", tip: "Bagagem" },
  { id: 6, word: "SUITCASE", tip: "Mala" },
  { id: 7, word: "PASSPORT", tip: "Passaporte" },
  { id: 8, word: "TICKET", tip: "Bilhete / Passagem" },
  { id: 9, word: "BOARDING GATE", tip: "Portão de embarque" },
  { id: 10, word: "ARRIVAL", tip: "Chegada" },
  { id: 11, word: "DEPARTURE", tip: "Partida" },
  { id: 12, word: "CUSTOMS", tip: "Alfândega" },
  { id: 13, word: "SECURITY CHECK", tip: "Verificação de segurança" },
  { id: 14, word: "HOTEL", tip: "Hotel" },
  { id: 15, word: "RESERVATION", tip: "Reserva" },
  { id: 16, word: "RECEPTION", tip: "Recepção" },
  { id: 17, word: "ROOM KEY", tip: "Chave do quarto" },
  { id: 18, word: "CHECK-IN", tip: "Fazer o check-in" },
  { id: 19, word: "CHECK-OUT", tip: "Fazer o check-out" },
  { id: 20, word: "MAP", tip: "Mapa" },
  { id: 21, word: "TOURIST", tip: "Turista" },
  { id: 22, word: "TOUR", tip: "Passeio / Excursão" },
  { id: 23, word: "MUSEUM", tip: "Museu" },
  { id: 24, word: "BEACH", tip: "Praia" },
  { id: 25, word: "CITY CENTER", tip: "Centro da cidade" },
  { id: 26, word: "TAXI", tip: "Táxi" },
  { id: 27, word: "BUS STATION", tip: "Rodoviária" },
  { id: 28, word: "TRAIN STATION", tip: "Estação de trem" },
  { id: 29, word: "SUBWAY", tip: "Metrô" },
  { id: 30, word: "CAR RENTAL", tip: "Aluguel de carro" },
  { id: 31, word: "TRAVEL INSURANCE", tip: "Seguro de viagem" },
  { id: 32, word: "TOUR GUIDE", tip: "Guia turístico" },
  { id: 33, word: "RESTAURANT", tip: "Restaurante" },
  { id: 34, word: "MENU", tip: "Cardápio" },
  { id: 35, word: "BILL", tip: "Conta (em restaurante)" },
  { id: 36, word: "TIP", tip: "Gorjeta" },
  { id: 37, word: "TICKET OFFICE", tip: "Bilheteria" },
  { id: 38, word: "TRAVEL AGENCY", tip: "Agência de viagens" },
  { id: 39, word: "DESTINATION", tip: "Destino" },
  { id: 40, word: "VACATION", tip: "Férias" },
  { id: 41, word: "SIGHTSEEING", tip: "Passeio turístico" },
  { id: 42, word: "PHOTO", tip: "Foto" },
  { id: 43, word: "SUNSCREEN", tip: "Protetor solar" },
  { id: 44, word: "BACKPACK", tip: "Mochila" },
  { id: 45, word: "GUIDEBOOK", tip: "Guia de viagem (livro)" },
  { id: 46, word: "LANGUAGE", tip: "Idioma" },
  { id: 47, word: "CURRENCY", tip: "Moeda" },
  { id: 48, word: "EXCHANGE RATE", tip: "Taxa de câmbio" },
  { id: 49, word: "TRAVELER", tip: "Viajante" },
  { id: 50, word: "ADVENTURE", tip: "Aventura" },
]
