import type { Challenge } from "../types"

export const WORDS_TRAVEL: Challenge[] = [
  { id: 151, word: "AIRPORT", tip: "Aeroporto", phonetic: "/ˈer.pɔːrt/", example: "We arrived at the airport two hours early.", examplePt: "Chegamos ao aeroporto duas horas antes." },
  { id: 152, word: "PLANE", tip: "Avião", phonetic: "/pleɪn/", example: "The plane lands in thirty minutes.", examplePt: "O avião pousa em trinta minutos." },
  { id: 153, word: "FLIGHT", tip: "Voo", phonetic: "/flaɪt/", example: "Have a safe flight!", examplePt: "Tenha um bom voo!" },
  { id: 154, word: "BOARDING PASS", tip: "Cartão de embarque", phonetic: "/ˈbɔːr.dɪŋ ˌpæs/", example: "Have your boarding pass ready.", examplePt: "Tenha seu cartão de embarque em mãos." },
  { id: 155, word: "LUGGAGE", tip: "Bagagem", phonetic: "/ˈlʌɡ.ɪdʒ/", example: "Where can I collect my luggage?", examplePt: "Onde posso retirar minha bagagem?" },
  { id: 156, word: "SUITCASE", tip: "Mala", phonetic: "/ˈsuːt.keɪs/", example: "My suitcase is very heavy.", examplePt: "Minha mala está muito pesada." },
  { id: 157, word: "PASSPORT", tip: "Passaporte", phonetic: "/ˈpæs.pɔːrt/", example: "Keep your passport in a safe pocket.", examplePt: "Mantenha seu passaporte em um bolso seguro." },
  { id: 158, word: "TICKET", tip: "Bilhete / Passagem", phonetic: "/ˈtɪk.ɪt/", example: "Show your train ticket to the inspector.", examplePt: "Mostre sua passagem de trem ao fiscal." },
  { id: 159, word: "BOARDING GATE", tip: "Portão de embarque", phonetic: "/ˈbɔːr.dɪŋ ɡeɪt/", example: "Our flight departs from gate 12.", examplePt: "Nosso voo sai do portão 12." },
  { id: 160, word: "ARRIVAL", tip: "Chegada", phonetic: "/əˈraɪ.vəl/", example: "The estimated arrival time is 4 PM.", examplePt: "O horário previsto de chegada é 16h." },
  { id: 161, word: "DEPARTURE", tip: "Partida", phonetic: "/dɪˈpɑːr.tʃɚ/", example: "Check the departure screen.", examplePt: "Verifique a tela de partidas." },
  { id: 162, word: "CUSTOMS", tip: "Alfândega", phonetic: "/ˈkʌs.təmz/", example: "We walked through customs quickly.", examplePt: "Passamos pela alfândega rapidamente." },
  { id: 163, word: "SECURITY CHECK", tip: "Verificação de segurança", phonetic: "/səˈkjʊr.ə.t̬i tʃek/", example: "Remove your shoes at security check.", examplePt: "Tire seus sapatos na inspeção de segurança." },
  { id: 164, word: "HOTEL", tip: "Hotel", phonetic: "/hoʊˈtel/", example: "The hotel is near the city center.", examplePt: "O hotel fica perto do centro da cidade." },
  { id: 165, word: "RESERVATION", tip: "Reserva", phonetic: "/ˌrez.ɚˈveɪ.ʃən/", example: "I have a hotel reservation for two nights.", examplePt: "Tenho uma reserva de hotel para duas noites." },
  { id: 166, word: "RECEPTION", tip: "Recepção", phonetic: "/rɪˈsep.ʃən/", example: "Ask for help at the front reception desk.", examplePt: "Peça ajuda no balcão da recepção." },
  { id: 167, word: "ROOM KEY", tip: "Chave do quarto", phonetic: "/ruːm kiː/", example: "Do not forget your room key.", examplePt: "Não se esqueça da chave do seu quarto." },
  { id: 168, word: "CHECK-IN", tip: "Fazer o check-in", phonetic: "/ˈtʃek.ɪn/", example: "Hotel check-in starts at 3 PM.", examplePt: "O check-in do hotel começa às 15h." },
  { id: 169, word: "CHECK-OUT", tip: "Fazer o check-out", phonetic: "/ˈtʃek.aʊt/", example: "Check-out time is before noon.", examplePt: "O horário de check-out é antes do meio-dia." },
  { id: 170, word: "MAP", tip: "Mapa", phonetic: "/mæp/", example: "Look at the tourist map.", examplePt: "Olhe no mapa turístico." },
  { id: 171, word: "TOURIST", tip: "Turista", phonetic: "/ˈtʊr.ɪst/", example: "Many tourists visit this historical monument.", examplePt: "Muitos turistas visitam este monumento histórico." },
  { id: 172, word: "TOUR", tip: "Passeio / Excursão", phonetic: "/tʊr/", example: "We booked a walking tour.", examplePt: "Nós reservamos um passeio a pé." },
  { id: 173, word: "MUSEUM", tip: "Museu", phonetic: "/mjuːˈziː.əm/", example: "The art museum is closed on Mondays.", examplePt: "O museu de arte está fechado às segundas-feiras." },
  { id: 174, word: "BEACH", tip: "Praia", phonetic: "/biːtʃ/", example: "Let's spend the afternoon at the beach.", examplePt: "Vamos passar a tarde na praia." },
  { id: 175, word: "CITY CENTER", tip: "Centro da cidade", phonetic: "/ˌsɪt.i ˈsen.t̬ɚ/", example: "Everything is close in the city center.", examplePt: "Tudo é perto no centro da cidade." },
  { id: 176, word: "TAXI", tip: "Táxi", phonetic: "/ˈtæk.si/", example: "Call a taxi to go to the station.", examplePt: "Chame um táxi para ir até a estação." },
  { id: 177, word: "BUS STATION", tip: "Rodoviária", phonetic: "/ˈbʌs ˌsteɪ.ʃən/", example: "The bus station is two blocks away.", examplePt: "A rodoviária fica a dois quarteirões." },
  { id: 178, word: "TRAIN STATION", tip: "Estação de trem", phonetic: "/ˈtreɪn ˌsteɪ.ʃən/", example: "Meet me inside the train station.", examplePt: "Encontre-me dentro da estação de trem." },
  { id: 179, word: "SUBWAY", tip: "Metrô", phonetic: "/ˈsʌb.weɪ/", example: "The subway is the fastest way around.", examplePt: "O metrô é a forma mais rápida de se locomover." },
  { id: 180, word: "CAR RENTAL", tip: "Aluguel de carro", phonetic: "/ˈkɑːr ˌren.t̬əl/", example: "We got a vehicle at the car rental.", examplePt: "Pegamos um veículo na locadora de carros." },
  { id: 181, word: "TRAVEL INSURANCE", tip: "Seguro de viagem", phonetic: "/ˈtræv.əl ɪnˌʃʊr.əns/", example: "Always purchase travel insurance before flying.", examplePt: "Sempre compre seguro de viagem antes de voar." },
  { id: 182, word: "TOUR GUIDE", tip: "Guia turístico", phonetic: "/ˈtʊr ˌɡaɪd/", example: "Our tour guide explained the whole history.", examplePt: "Nosso guia turístico explicou toda a história." },
  { id: 183, word: "RESTAURANT", tip: "Restaurante", phonetic: "/ˈres.trɑːnt/", example: "Can you recommend a good local restaurant?", examplePt: "Pode recomendar um bom restaurante local?" },
  { id: 184, word: "MENU", tip: "Cardápio", phonetic: "/ˈmen.juː/", example: "Could we see the dessert menu, please?", examplePt: "Poderíamos ver o cardápio de sobremesas, por favor?" },
  { id: 185, word: "BILL", tip: "Conta (em restaurante)", phonetic: "/bɪl/", example: "Could we have the bill, please?", examplePt: "Poderia trazer a conta, por favor?" },
  { id: 186, word: "TIP", tip: "Gorjeta", phonetic: "/tɪp/", example: "We left a generous tip for the waiter.", examplePt: "Deixamos uma gorjeta generosa para o garçom." },
  { id: 187, word: "TICKET OFFICE", tip: "Bilheteria", phonetic: "/ˈtɪk.ɪt ˌɑː.fɪs/", example: "Buy your pass at the ticket office.", examplePt: "Compre seu passe na bilheteria." },
  { id: 188, word: "TRAVEL AGENCY", tip: "Agência de viagens", phonetic: "/ˈtræv.əl ˌeɪ.dʒən.si/", example: "They planned their honeymoon with a travel agency.", examplePt: "Eles planejaram a lua de mel com uma agência de viagens." },
  { id: 189, word: "DESTINATION", tip: "Destino", phonetic: "/ˌdes.təˈneɪ.ʃən/", example: "Paris is a world-famous travel destination.", examplePt: "Paris é um destino de viagem mundialmente famoso." },
  { id: 190, word: "VACATION", tip: "Férias", phonetic: "/veɪˈkeɪ.ʃən/", example: "I am going on vacation next month.", examplePt: "Vou sair de férias no próximo mês." },
  { id: 191, word: "SIGHTSEEING", tip: "Passeio turístico", phonetic: "/ˈsaɪtˌsiː.ɪŋ/", example: "We spent the whole day sightseeing.", examplePt: "Passamos o dia inteiro fazendo passeios turísticos." },
  { id: 192, word: "PHOTO", tip: "Foto", phonetic: "/ˈfoʊ.toʊ/", example: "Could you take a photo of us?", examplePt: "Poderia tirar uma foto nossa?" },
  { id: 193, word: "SUNSCREEN", tip: "Protetor solar", phonetic: "/ˈsʌn.skriːn/", example: "Apply sunscreen before going into the sun.", examplePt: "Aplique protetor solar antes de ir ao sol." },
  { id: 194, word: "BACKPACK", tip: "Mochila", phonetic: "/ˈbæk.pæk/", example: "He travels with just a light backpack.", examplePt: "Ele viaja apenas com uma mochila leve." },
  { id: 195, word: "GUIDEBOOK", tip: "Guia de viagem (livro)", phonetic: "/ˈɡaɪd.bʊk/", example: "Check the recommendations in the guidebook.", examplePt: "Verifique as recomendações no livro-guia." },
  { id: 196, word: "LANGUAGE", tip: "Idioma", phonetic: "/ˈlæŋ.ɡwɪdʒ/", example: "English is an international language.", examplePt: "O inglês é um idioma internacional." },
  { id: 197, word: "CURRENCY", tip: "Moeda (dinheiro)", phonetic: "/ˈkɝː.ən.si/", example: "What is the local currency here?", examplePt: "Qual é a moeda local aqui?" },
  { id: 198, word: "EXCHANGE RATE", tip: "Taxa de câmbio", phonetic: "/ɪksˈtʃeɪndʒ ˌreɪt/", example: "Check the currency exchange rate today.", examplePt: "Confira a taxa de câmbio hoje." },
  { id: 199, word: "TRAVELER", tip: "Viajante", phonetic: "/ˈtræv.əl.ɚ/", example: "He is an experienced world traveler.", examplePt: "Ele é um viajante experiente pelo mundo." },
  { id: 200, word: "ADVENTURE", tip: "Aventura", phonetic: "/ədˈven.tʃɚ/", example: "Life is a great adventure.", examplePt: "A vida é uma grande aventura." },
]
